// Simplified persona definitions with merged content

export interface PersonaDefinition {
  id: string
  label: string
  department: 'Operations' | 'Finance' | 'Logistics' | 'Supply Chain' | 'Sourcing Procurement'
  seniority: 'C-Suite' | 'Upper Management' | 'Middle Management' | 'Entry Level' | 'Intern'
  painPoints: string[]
  toneProfile: string
  keywords: string[]
}

export const PERSONA_DEFINITIONS: PersonaDefinition[] = [
  // C-Suite Level
  {
    id: 'ceo',
    label: 'CEO',
    department: 'Operations',
    seniority: 'C-Suite',
    painPoints: [
      'Strategic Challenges: balancing shareholder demands for profitability with resilient, sustainable freight procurement',
      'Strategic Challenges: limited visibility into how freight costs impact overall corporate strategy',
      'Strategic Challenges: difficulty aligning freight procurement with growth goals',
      'Operational Pain Points: fragmented procurement practices across business units reducing efficiency',
      'Operational Pain Points: over-reliance on outdated procurement models that limit agility',
      'Operational Pain Points: inefficient communication between freight procurement and other strategic functions (finance, sales, operations)',
      'Cost & Budget Concerns: freight spend volatility creating uncertainty for earnings forecasts',
      'Cost & Budget Concerns: difficulty ensuring procurement cost savings flow through to P&L results',
      'Cost & Budget Concerns: unpredictable global freight markets affecting long-term financial planning',
      'Risk & Compliance: exposure to high-profile disruptions (geopolitical, climate, regulatory)',
      'Risk & Compliance: insufficient processes to safeguard against fraud or weak carrier vetting',
      'Technology & Data Gaps: lack of enterprise-wide freight visibility tools tied to executive dashboards',
      'Technology & Data Gaps: disparate systems that limit a single view of procurement impact',
      'Technology & Data Gaps: slow adoption of modern freight procurement technologies across regions',
      'Carrier & Supplier Management: difficulty balancing reliance on strategic partners with need for diversification',
      'Carrier & Supplier Management: limited visibility into supplier/carrier health and performance at board level',
      'Carrier & Supplier Management: tensions between cost-driven decisions and long-term relationship building',
      'Talent & Organizational Pressures: pressure on leadership to attract talent capable of modernizing freight procurement',
      'Talent & Organizational Pressures: need to foster cross-functional collaboration between finance, procurement, and operations'
    ],
    toneProfile: 'Be direct and decisive – cut to the chase with the big picture. Focus on outcomes and strategy – emphasize long-term vision, market position, and competitive edge. Use high-level language – avoid operational details unless directly tied to business growth or risk. Concise but compelling – short, impactful phrasing that reinforces urgency and direction. CRITICAL: Use simple, clear language – avoid complex jargon like "leverage", "synergies", "scalability optimization", "enterprise integration". Use everyday words that anyone can understand.',
    keywords: ['strategic', 'enterprise', 'roi', 'scalability', 'executive', 'board', 'competitive advantage', 'enterprise-wide']
  },
  {
    id: 'president',
    label: 'President',
    department: 'Operations',
    seniority: 'C-Suite',
    painPoints: [
      'Strategic Challenges: balancing shareholder demands for profitability with resilient, sustainable freight procurement',
      'Strategic Challenges: limited visibility into how freight costs impact overall corporate strategy',
      'Strategic Challenges: difficulty aligning freight procurement with growth goals',
      'Operational Pain Points: fragmented procurement practices across business units reducing efficiency',
      'Operational Pain Points: over-reliance on outdated procurement models that limit agility',
      'Operational Pain Points: inefficient communication between freight procurement and other strategic functions (finance, sales, operations)',
      'Cost & Budget Concerns: freight spend volatility creating uncertainty for earnings forecasts',
      'Cost & Budget Concerns: difficulty ensuring procurement cost savings flow through to P&L results',
      'Cost & Budget Concerns: unpredictable global freight markets affecting long-term financial planning',
      'Risk & Compliance: exposure to high-profile disruptions (geopolitical, climate, regulatory)',
      'Risk & Compliance: insufficient processes to safeguard against fraud or weak carrier vetting',
      'Technology & Data Gaps: lack of enterprise-wide freight visibility tools tied to executive dashboards',
      'Technology & Data Gaps: disparate systems that limit a single view of procurement impact',
      'Technology & Data Gaps: slow adoption of modern freight procurement technologies across regions',
      'Carrier & Supplier Management: difficulty balancing reliance on strategic partners with need for diversification',
      'Carrier & Supplier Management: limited visibility into supplier/carrier health and performance at board level',
      'Carrier & Supplier Management: tensions between cost-driven decisions and long-term relationship building',
      'Talent & Organizational Pressures: pressure on leadership to attract talent capable of modernizing freight procurement',
      'Talent & Organizational Pressures: need to foster cross-functional collaboration between finance, procurement, and operations'
    ],
    toneProfile: 'Be direct and decisive – cut to the chase with the big picture. Focus on outcomes and strategy – emphasize long-term vision, market position, and competitive edge. Use high-level language – avoid operational details unless directly tied to business growth or risk. Concise but compelling – short, impactful phrasing that reinforces urgency and direction. CRITICAL: Use simple, clear language – avoid complex jargon like "leverage", "synergies", "scalability optimization", "enterprise integration". Use everyday words that anyone can understand.',
    keywords: ['strategic', 'enterprise', 'roi', 'scalability', 'executive', 'board', 'competitive advantage', 'enterprise-wide']
  },
  {
    id: 'coo',
    label: 'COO',
    department: 'Operations',
    seniority: 'C-Suite',
    painPoints: [
      'Strategic Challenges: translating the CEO\'s vision into executable operational strategies',
      'Strategic Challenges: balancing operational efficiency with cost optimization across all business functions',
      'Strategic Challenges: difficulty in maintaining operational flexibility while also committing to long-term strategic partnerships',
      'Operational Pain Points: fragmented processes across regions, modes, and business units that hinder standardization',
      'Operational Pain Points: manual, time-consuming operational planning and execution processes',
      'Operational Pain Points: high administrative overhead due to managing multiple operational functions and vendors',
      'Operational Pain Points: lack of real-time visibility into operational performance, exceptions, and disruptions',
      'Cost & Budget Concerns: volatile operational costs driven by market conditions, capacity constraints, and external factors',
      'Cost & Budget Concerns: limited ability to benchmark operational performance effectively due to inconsistent data',
      'Cost & Budget Concerns: difficulty in proving and tracking operational efficiency improvements to executive stakeholders',
      'Cost & Budget Concerns: over-reliance on reactive approaches during operational challenges, leading to unplanned cost spikes',
      'Risk & Compliance: exposure to operational disruptions (supply chain issues, regulatory changes, market volatility)',
      'Risk & Compliance: risk of vendor/partner underperformance affecting operational service levels',
      'Risk & Compliance: lack of standardized processes for vendor/partner vetting and performance management',
      'Technology & Data Gaps: disparate systems across operations, procurement, and finance teams that don\'t integrate',
      'Technology & Data Gaps: poor quality or incomplete operational data limiting analytics and decision-making',
      'Technology & Data Gaps: difficulty adopting modern digital operational management tools at scale',
      'Technology & Data Gaps: resistance to change from teams accustomed to legacy/manual processes',
      'Vendor & Partner Management: maintaining strong relationships with vendors while also pushing for better performance and rates',
      'Vendor & Partner Management: balancing strategic partnerships with the need for diversification to reduce dependency',
      'Vendor & Partner Management: limited visibility into vendor/partner performance metrics and KPIs across functions',
      'Vendor & Partner Management: difficulty in negotiating fair contract terms during volatile market conditions',
      'Talent & Organizational Pressures: shortage of operational professionals with advanced analytics and digital skills',
      'Talent & Organizational Pressures: high expectations from executive leadership to deliver operational efficiency improvements quickly',
      'Talent & Organizational Pressures: challenges in retaining top talent in a competitive operational labor market'
    ],
    toneProfile: 'Be strategic with operational depth – balance long-term goals with actionable next steps. Use comparative insights – benchmark performance, highlight best practices. Show resource allocation impact – budgets, technology adoption, vendor choices. Confident and professional – present clear recommendations backed by data. CRITICAL: Use simple, clear language – avoid complex jargon like "centralize", "validate", "leverage", "optimize", "visibility". Use everyday words that anyone can understand.',
    keywords: ['operational', 'management', 'efficiency', 'team', 'process', 'departmental', 'leadership', 'productivity']
  },
  {
    id: 'cfo',
    label: 'CFO',
    department: 'Finance',
    seniority: 'C-Suite',
    painPoints: [
      'Strategic & Financial Pressure: balancing short-term cost-cutting with long-term investment and growth strategies',
      'Strategic & Financial Pressure: increasing pressure from boards and investors for predictable financial performance',
      'Strategic & Financial Pressure: difficulty in forecasting accurately amid economic volatility, currency fluctuations, and market uncertainty',
      'Strategic & Financial Pressure: pressure to provide actionable insights beyond reporting (acting as a strategic partner vs. back-office)',
      'Operational Inefficiencies: reliance on outdated ERP/financial systems that require manual data reconciliation',
      'Operational Inefficiencies: complex, time-consuming month-end and quarter-end close processes',
      'Operational Inefficiencies: inconsistent processes across regions/business units, slowing down consolidation',
      'Data & Reporting Challenges: lack of real-time visibility into company supply chain health across operations',
      'Data & Reporting Challenges: struggles with data quality, accuracy, and consistency when pulling from multiple systems',
      'Data & Reporting Challenges: limited automation in reporting, leading to heavy reliance on spreadsheets',
      'Data & Reporting Challenges: difficulty delivering timely insights to executives due to manual reporting cycles',
      'Data & Reporting Challenges: regulatory reporting requirements that demand higher precision and audit-ability',
      'Technology Limitations: difficulty justifying ROI on finance digital transformation projects',
      'Technology Limitations: limited integration between ERP, BI, and planning systems',
      'Technology Limitations: struggles with implementing advanced analytics, AI, or automation due to data silos',
      'Talent & Organizational Issues: gaps in advanced analytics, automation, and digital finance capabilities among staff',
      'Talent & Organizational Issues: misalignment between finance priorities and operational/business unit leaders'
    ],
    toneProfile: 'Be strategic with operational depth – balance long-term goals with actionable next steps. Use comparative insights – benchmark performance, highlight best practices. Show resource allocation impact – budgets, technology adoption, vendor choices. Confident and professional – present clear recommendations backed by data. CRITICAL: Use simple, clear language – avoid complex financial jargon like "accruals", "reconciliations", "GR/IR matching", "variance", "true-up". Use everyday words that anyone can understand.',
    keywords: ['financial', 'management', 'departmental', 'controls', 'team', 'leadership', 'performance', 'planning']
  },
  {
    id: 'csco',
    label: 'CSCO (Chief Supply Chain Officer)',
    department: 'Operations',
    seniority: 'C-Suite',
    painPoints: [
      'Strategic Challenges: balancing cost optimization with service reliability and customer expectations',
      'Strategic Challenges: limited visibility into end-to-end supply chain costs, making it hard to forecast and budget accurately',
      'Strategic Challenges: difficulty in maintaining flexibility while also committing to long-term supply chain partnerships',
      'Operational Pain Points: fragmented processes across regions, modes, and business units that hinder standardization',
      'Operational Pain Points: manual, time-consuming supply chain planning and execution processes',
      'Operational Pain Points: high administrative overhead due to managing multiple supply chain functions and partners',
      'Operational Pain Points: lack of real-time visibility into supply chain performance, exceptions, and disruptions',
      'Cost & Budget Concerns: volatile supply chain costs driven by market conditions, capacity constraints, and external factors',
      'Cost & Budget Concerns: limited ability to benchmark supply chain performance effectively due to inconsistent data',
      'Cost & Budget Concerns: difficulty in proving and tracking supply chain efficiency improvements to executive stakeholders',
      'Cost & Budget Concerns: over-reliance on reactive approaches during supply chain challenges, leading to unplanned cost spikes',
      'Risk & Compliance: exposure to supply chain disruptions (geopolitical, climate, regulatory, market volatility)',
      'Risk & Compliance: risk of supply chain partner underperformance affecting service levels',
      'Risk & Compliance: lack of standardized processes for supply chain partner vetting and performance management',
      'Technology & Data Gaps: disparate systems across supply chain, procurement, and finance teams that don\'t integrate',
      'Technology & Data Gaps: poor quality or incomplete supply chain data limiting analytics and decision-making',
      'Technology & Data Gaps: difficulty adopting modern digital supply chain management tools at scale',
      'Technology & Data Gaps: resistance to change from teams accustomed to legacy/manual processes',
      'Partner & Supplier Management: maintaining strong relationships with supply chain partners while also pushing for better performance and rates',
      'Partner & Supplier Management: balancing strategic partnerships with the need for diversification to reduce dependency',
      'Partner & Supplier Management: limited visibility into supply chain partner performance metrics and KPIs across functions',
      'Partner & Supplier Management: difficulty in negotiating fair contract terms during volatile market conditions',
      'Talent & Organizational Pressures: shortage of supply chain professionals with advanced analytics and digital skills',
      'Talent & Organizational Pressures: high expectations from executive leadership to deliver supply chain efficiency improvements quickly',
      'Talent & Organizational Pressures: challenges in retaining top talent in a competitive supply chain labor market'
    ],
    toneProfile: 'Be strategic with operational depth – balance long-term goals with actionable next steps. Use comparative insights – benchmark performance, highlight best practices. Show resource allocation impact – budgets, technology adoption, vendor choices. Confident and professional – present clear recommendations backed by data. CRITICAL: Use simple, clear language – avoid complex jargon like "centralize", "validate", "leverage", "optimize", "visibility". Use everyday words that anyone can understand.',
    keywords: ['supply chain', 'management', 'efficiency', 'team', 'process', 'departmental', 'leadership', 'productivity']
  },
  // Operations Department
  {
    id: 'operations_management',
    label: 'Operations Management',
    department: 'Operations',
    seniority: 'Upper Management',
    painPoints: [
      'Strategic Challenges: balancing cost optimization with service reliability and customer expectations',
      'Strategic Challenges: limited visibility into end-to-end operational costs, making it hard to forecast and budget accurately',
      'Strategic Challenges: difficulty in maintaining flexibility while also committing to long-term operational partnerships',
      'Operational Pain Points: fragmented processes across regions, modes, and business units that hinder standardization',
      'Operational Pain Points: manual, time-consuming operational planning and execution processes',
      'Operational Pain Points: high administrative overhead due to managing multiple operational functions and partners',
      'Operational Pain Points: lack of real-time visibility into operational performance, exceptions, and disruptions',
      'Execution & Day-to-Day Firefighting: constantly dealing with last-minute operational changes, delays, and disruptions',
      'Execution & Day-to-Day Firefighting: difficulty reallocating resources when partners reject requests or fail to perform',
      'Execution & Day-to-Day Firefighting: overwhelmed by daily problem-solving instead of focusing on proactive improvements',
      'Execution & Day-to-Day Firefighting: struggles managing exceptions in real time (delays, quality issues, compliance problems)',
      'Cost & Budget Concerns: volatile operational costs driven by market conditions, capacity constraints, and external factors',
      'Cost & Budget Concerns: limited ability to benchmark operational performance effectively due to inconsistent data',
      'Cost & Budget Concerns: difficulty in proving and tracking operational efficiency improvements to executive stakeholders',
      'Cost & Budget Concerns: over-reliance on reactive approaches during operational challenges, leading to unplanned cost spikes',
      'Risk & Compliance: exposure to operational disruptions (supply chain issues, regulatory changes, market volatility)',
      'Risk & Compliance: risk of vendor/partner underperformance affecting operational service levels',
      'Risk & Compliance: lack of standardized processes for vendor/partner vetting and performance management',
      'Technology & Data Gaps: disparate systems across operations, procurement, and finance teams that don\'t integrate',
      'Technology & Data Gaps: poor quality or incomplete operational data limiting analytics and decision-making',
      'Technology & Data Gaps: difficulty adopting modern digital operational management tools at scale',
      'Technology & Data Gaps: resistance to change from teams accustomed to legacy/manual processes',
      'Vendor & Partner Management: maintaining strong relationships with vendors while also pushing for better performance and rates',
      'Vendor & Partner Management: balancing strategic partnerships with the need for diversification to reduce dependency',
      'Vendor & Partner Management: limited visibility into vendor/partner performance metrics and KPIs across functions',
      'Vendor & Partner Management: difficulty in negotiating fair contract terms during volatile market conditions',
      'Talent & Organizational Pressures: shortage of operational professionals with advanced analytics and digital skills',
      'Talent & Organizational Pressures: high expectations from executive leadership to deliver operational efficiency improvements quickly',
      'Talent & Organizational Pressures: challenges in retaining top talent in a competitive operational labor market'
    ],
    toneProfile: 'Be strategic with operational depth – balance long-term goals with actionable next steps. Use comparative insights – benchmark performance, highlight best practices. Show resource allocation impact – budgets, technology adoption, vendor choices. Confident and professional – present clear recommendations backed by data. Be actionable and tactical – focus on "what needs to happen next." Provide clarity and guidance – simplify priorities for their teams. Problem-solving tone – address bottlenecks, performance issues, and team management. Collaborative but firm – engage them in decisions while setting clear expectations. CRITICAL: Use simple, clear language – avoid complex jargon like "centralize", "validate", "leverage", "optimize", "visibility". Use everyday words that anyone can understand.',
    keywords: ['operational', 'management', 'efficiency', 'team', 'process', 'departmental', 'leadership', 'productivity', 'practical', 'execution', 'coordination', 'solutions']
  },
  {
    id: 'operations_entry_level',
    label: 'Operations Entry Level',
    department: 'Operations',
    seniority: 'Entry Level',
    painPoints: [
      'Learning & Skill Development: steep learning curve for understanding complex operational processes and systems',
      'Learning & Skill Development: lack of comprehensive training on operational best practices and industry standards',
      'Learning & Skill Development: difficulty understanding how individual tasks fit into broader operational objectives',
      'Learning & Skill Development: limited mentorship opportunities from senior operational professionals',
      'Process & System Challenges: navigating complex operational systems and tools without proper guidance',
      'Process & System Challenges: difficulty understanding operational workflows and decision-making processes',
      'Process & System Challenges: lack of clear documentation for operational procedures and protocols',
      'Process & System Challenges: struggling with data entry and system navigation in operational platforms',
      'Communication & Coordination: difficulty communicating effectively with senior management and cross-functional teams',
      'Communication & Coordination: lack of confidence in presenting operational findings or recommendations',
      'Communication & Coordination: challenges in understanding operational terminology and industry jargon',
      'Communication & Coordination: difficulty building relationships with operational partners and vendors',
      'Performance & Expectations: pressure to meet operational targets without sufficient experience or training',
      'Performance & Expectations: difficulty understanding operational KPIs and performance metrics',
      'Performance & Expectations: lack of feedback on operational performance and areas for improvement',
      'Performance & Expectations: challenges in prioritizing operational tasks and managing workload effectively',
      'Technology & Tools: difficulty adapting to new operational technologies and digital tools',
      'Technology & Tools: lack of training on operational software and systems',
      'Technology & Tools: challenges in understanding operational data and analytics',
      'Technology & Tools: difficulty troubleshooting operational system issues and technical problems'
    ],
    toneProfile: 'Be patient and explanatory – over-communicate to ensure understanding. Keep it simple and structured – clear tasks, step-by-step guidance. Encouraging and mentoring – foster curiosity and confidence. Positive and approachable – tone should reduce intimidation and promote engagement.',
    keywords: ['learning', 'exploration', 'discovery', 'mentorship', 'growth', 'experience', 'development', 'opportunity']
  },
  {
    id: 'operations_intern',
    label: 'Operations Intern',
    department: 'Operations',
    seniority: 'Intern',
    painPoints: [
      'Learning & Skill Development: steep learning curve for understanding operational processes and industry basics',
      'Learning & Skill Development: lack of comprehensive training on operational fundamentals and best practices',
      'Learning & Skill Development: difficulty understanding how operational tasks contribute to business objectives',
      'Learning & Skill Development: limited exposure to real-world operational challenges and solutions',
      'Process & System Challenges: navigating operational systems and tools for the first time',
      'Process & System Challenges: difficulty understanding operational workflows and decision-making processes',
      'Process & System Challenges: lack of clear documentation for operational procedures and protocols',
      'Process & System Challenges: struggling with basic operational tasks and system navigation',
      'Communication & Coordination: difficulty communicating effectively with operational teams and management',
      'Communication & Coordination: lack of confidence in asking questions or seeking help',
      'Communication & Coordination: challenges in understanding operational terminology and industry concepts',
      'Communication & Coordination: difficulty building relationships with operational colleagues and mentors',
      'Performance & Expectations: pressure to learn quickly and contribute meaningfully to operational projects',
      'Performance & Expectations: difficulty understanding operational goals and success metrics',
      'Performance & Expectations: lack of feedback on operational work and areas for improvement',
      'Performance & Expectations: challenges in managing time and prioritizing operational tasks',
      'Technology & Tools: difficulty adapting to operational technologies and digital tools',
      'Technology & Tools: lack of training on operational software and systems',
      'Technology & Tools: challenges in understanding operational data and basic analytics',
      'Technology & Tools: difficulty troubleshooting basic operational system issues'
    ],
    toneProfile: 'Be patient and explanatory – over-communicate to ensure understanding. Keep it simple and structured – clear tasks, step-by-step guidance. Encouraging and mentoring – foster curiosity and confidence. Positive and approachable – tone should reduce intimidation and promote engagement.',
    keywords: ['learning', 'exploration', 'discovery', 'mentorship', 'growth', 'experience', 'development', 'opportunity']
  },
  // Finance Department
  {
    id: 'finance_management',
    label: 'Finance Management',
    department: 'Finance',
    seniority: 'Upper Management',
    painPoints: [
      'Strategic & Financial Pressure: balancing short-term cost-cutting with long-term investment and growth strategies',
      'Strategic & Financial Pressure: increasing pressure from boards and investors for predictable financial performance',
      'Strategic & Financial Pressure: difficulty in forecasting accurately amid economic volatility, currency fluctuations, and market uncertainty',
      'Strategic & Financial Pressure: pressure to provide actionable insights beyond reporting (acting as a strategic partner vs. back-office)',
      'Operational Inefficiencies: reliance on outdated ERP/financial systems that require manual data reconciliation',
      'Operational Inefficiencies: complex, time-consuming month-end and quarter-end close processes',
      'Operational Inefficiencies: inconsistent processes across regions/business units, slowing down consolidation',
      'Data & Reporting Challenges: lack of real-time visibility into company supply chain health across operations',
      'Data & Reporting Challenges: struggles with data quality, accuracy, and consistency when pulling from multiple systems',
      'Data & Reporting Challenges: limited automation in reporting, leading to heavy reliance on spreadsheets',
      'Data & Reporting Challenges: difficulty delivering timely insights to executives due to manual reporting cycles',
      'Data & Reporting Challenges: regulatory reporting requirements that demand higher precision and audit-ability',
      'Technology Limitations: difficulty justifying ROI on finance digital transformation projects',
      'Technology Limitations: limited integration between ERP, BI, and planning systems',
      'Technology Limitations: struggles with implementing advanced analytics, AI, or automation due to data silos',
      'Talent & Organizational Issues: gaps in advanced analytics, automation, and digital finance capabilities among staff',
      'Talent & Organizational Issues: misalignment between finance priorities and operational/business unit leaders',
      'Cost Control & Budget Management: freight spend is highly variable and difficult to forecast due to rate volatility',
      'Cost Control & Budget Management: hidden surcharges (fuel, accessorials, detention, demurrage) make budgeting unpredictable',
      'Cost Control & Budget Management: inability to accurately allocate transportation costs to specific products, regions, or business units',
      'Cost Control & Budget Management: difficulty validating that negotiated carrier rates are actually being applied in invoices',
      'Cost Control & Budget Management: pressure to reduce logistics costs while balancing service-level requirements',
      'Freight Audit & Payment Challenges: manual invoice reconciliation leading to errors and delays',
      'Freight Audit & Payment Challenges: high volume of freight invoices creates administrative burden',
      'Freight Audit & Payment Challenges: difficulty matching invoices to contracts, shipments, and POs',
      'Freight Audit & Payment Challenges: carrier overbilling or duplicate charges slipping through without proper audit controls',
      'Data & Reporting Limitations: limited visibility into total landed cost and how freight affects product margins',
      'Data & Reporting Limitations: inconsistent data across procurement, logistics, and finance systems',
      'Data & Reporting Limitations: difficulty producing accurate financial reports for leadership or regulators',
      'Data & Reporting Limitations: lack of standardized KPIs to measure cost efficiency of procurement decisions',
      'Data & Reporting Limitations: struggles to provide real-time reporting to support operational decision-making',
      'Risk & Compliance: exposure to financial risks from fuel price spikes, capacity shortages, or tariff changes',
      'Cross-Department Coordination: misalignment between finance, procurement, and operations on cost-saving initiatives',
      'Cross-Department Coordination: difficulty validating savings claimed by procurement against actual financial outcomes',
      'Cross-Department Coordination: pressure from CFO/board to demonstrate ROI of procurement projects',
      'Cross-Department Coordination: tension between finance\'s need for strict controls and operations\' need for agility',
      'Cross-Department Coordination: lack of clear accountability for freight cost overruns between departments',
      'Technology & Systems Gaps: reliance on outdated freight payment systems or spreadsheets',
      'Technology & Systems Gaps: poor integration between TMS, ERP, and financial systems',
      'Technology & Systems Gaps: difficulty adopting modern spend analytics tools without disrupting existing processes',
      'Technology & Systems Gaps: high IT/security hurdles to integrate external freight platforms with finance systems',
      'Strategic Pressures: increasing demand to make freight spend more predictable for earnings guidance',
      'Strategic Pressures: difficulty balancing short-term cost savings with long-term supply chain resilience',
      'Strategic Pressures: pressure to identify cost-saving opportunities in freight without undermining service quality',
      'Strategic Pressures: challenges in quantifying the financial impact of disruptions (e.g., port congestion, strikes)'
    ],
    toneProfile: 'Be strategic with operational depth – balance long-term goals with actionable next steps. Use comparative insights – benchmark performance, highlight best practices. Show resource allocation impact – budgets, technology adoption, vendor choices. Confident and professional – present clear recommendations backed by data. Be actionable and tactical – focus on "what needs to happen next." Provide clarity and guidance – simplify priorities for their teams. Problem-solving tone – address bottlenecks, performance issues, and team management. Collaborative but firm – engage them in decisions while setting clear expectations. CRITICAL: Use simple, clear language – avoid complex financial jargon like "accruals", "reconciliations", "GR/IR matching", "variance", "true-up". Use everyday words that anyone can understand.',
    keywords: ['financial', 'management', 'departmental', 'controls', 'team', 'leadership', 'performance', 'planning', 'analysis', 'practical', 'execution', 'coordination', 'solutions']
  },
  {
    id: 'finance_entry_level',
    label: 'Finance Entry Level',
    department: 'Finance',
    seniority: 'Entry Level',
    painPoints: [
      'Learning & Skill Development: steep learning curve for understanding complex financial processes and systems',
      'Learning & Skill Development: lack of comprehensive training on financial best practices and industry standards',
      'Learning & Skill Development: difficulty understanding how individual tasks fit into broader financial objectives',
      'Learning & Skill Development: limited mentorship opportunities from senior financial professionals',
      'Process & System Challenges: navigating complex financial systems and tools without proper guidance',
      'Process & System Challenges: difficulty understanding financial workflows and decision-making processes',
      'Process & System Challenges: lack of clear documentation for financial procedures and protocols',
      'Process & System Challenges: struggling with data entry and system navigation in financial platforms',
      'Communication & Coordination: difficulty communicating effectively with senior management and cross-functional teams',
      'Communication & Coordination: lack of confidence in presenting financial findings or recommendations',
      'Communication & Coordination: challenges in understanding financial terminology and industry jargon',
      'Communication & Coordination: difficulty building relationships with financial partners and vendors',
      'Performance & Expectations: pressure to meet financial targets without sufficient experience or training',
      'Performance & Expectations: difficulty understanding financial KPIs and performance metrics',
      'Performance & Expectations: lack of feedback on financial performance and areas for improvement',
      'Performance & Expectations: challenges in prioritizing financial tasks and managing workload effectively',
      'Technology & Tools: difficulty adapting to new financial technologies and digital tools',
      'Technology & Tools: lack of training on financial software and systems',
      'Technology & Tools: challenges in understanding financial data and analytics',
      'Technology & Tools: difficulty troubleshooting financial system issues and technical problems'
    ],
    toneProfile: 'Be patient and explanatory – over-communicate to ensure understanding. Keep it simple and structured – clear tasks, step-by-step guidance. Encouraging and mentoring – foster curiosity and confidence. Positive and approachable – tone should reduce intimidation and promote engagement.',
    keywords: ['learning', 'exploration', 'discovery', 'mentorship', 'growth', 'experience', 'development', 'opportunity']
  },
  {
    id: 'finance_intern',
    label: 'Finance Intern',
    department: 'Finance',
    seniority: 'Intern',
    painPoints: [
      'Learning & Skill Development: steep learning curve for understanding financial processes and industry basics',
      'Learning & Skill Development: lack of comprehensive training on financial fundamentals and best practices',
      'Learning & Skill Development: difficulty understanding how financial tasks contribute to business objectives',
      'Learning & Skill Development: limited exposure to real-world financial challenges and solutions',
      'Process & System Challenges: navigating financial systems and tools for the first time',
      'Process & System Challenges: difficulty understanding financial workflows and decision-making processes',
      'Process & System Challenges: lack of clear documentation for financial procedures and protocols',
      'Process & System Challenges: struggling with basic financial tasks and system navigation',
      'Communication & Coordination: difficulty communicating effectively with financial teams and management',
      'Communication & Coordination: lack of confidence in asking questions or seeking help',
      'Communication & Coordination: challenges in understanding financial terminology and industry concepts',
      'Communication & Coordination: difficulty building relationships with financial colleagues and mentors',
      'Performance & Expectations: pressure to learn quickly and contribute meaningfully to financial projects',
      'Performance & Expectations: difficulty understanding financial goals and success metrics',
      'Performance & Expectations: lack of feedback on financial work and areas for improvement',
      'Performance & Expectations: challenges in managing time and prioritizing financial tasks',
      'Technology & Tools: difficulty adapting to financial technologies and digital tools',
      'Technology & Tools: lack of training on financial software and systems',
      'Technology & Tools: challenges in understanding financial data and basic analytics',
      'Technology & Tools: difficulty troubleshooting basic financial system issues'
    ],
    toneProfile: 'Be patient and explanatory – over-communicate to ensure understanding. Keep it simple and structured – clear tasks, step-by-step guidance. Encouraging and mentoring – foster curiosity and confidence. Positive and approachable – tone should reduce intimidation and promote engagement.',
    keywords: ['learning', 'exploration', 'discovery', 'mentorship', 'growth', 'experience', 'development', 'opportunity']
  }
]

// Helper functions
export function getPersonaById(id: string): PersonaDefinition | undefined {
  return PERSONA_DEFINITIONS.find(persona => persona.id === id)
}

export function getPersonasByDepartment(department: 'Operations' | 'Finance' | 'Logistics' | 'Supply Chain' | 'Sourcing Procurement'): PersonaDefinition[] {
  return PERSONA_DEFINITIONS.filter(persona => persona.department === department)
}

export function getPersonasBySeniority(seniority: 'C-Suite' | 'Upper Management' | 'Middle Management' | 'Entry Level' | 'Intern'): PersonaDefinition[] {
  return PERSONA_DEFINITIONS.filter(persona => persona.seniority === seniority)
}
