// Detailed persona definitions with pain points and tone profiles

export interface PersonaDefinition {
  id: string
  label: string
  department: 'Operations' | 'Finance' | 'Logistics' | 'Supply Chain' | 'Sourcing Procurement'
  seniority: 'C-Suite' | 'Upper Management' | 'Middle Management' | 'Entry Level' | 'Intern'
  painPoints: string[]
  toneProfile: string
  keywords: string[]
}

export const PERSONA_DEFINITIONS: PersonaDefinition[] = [
  // Operations Department
  {
    id: 'ceo',
    label: 'CEO',
    department: 'Operations',
    seniority: 'C-Suite',
    painPoints: [
      'Strategic Challenges: balancing shareholder demands for profitability with resilient, sustainable freight procurement',
      'Strategic Challenges: limited visibility into how freight costs impact overall corporate strategy',
      'Strategic Challenges: difficulty aligning freight procurement with growth goals',
      'Operational Pain Points: fragmented procurement practices across business units reducing efficiency',
      'Operational Pain Points: over-reliance on outdated procurement models that limit agility',
      'Operational Pain Points: inefficient communication between freight procurement and other strategic functions (finance, sales, operations)',
      'Cost & Budget Concerns: freight spend volatility creating uncertainty for earnings forecasts',
      'Cost & Budget Concerns: difficulty ensuring procurement cost savings flow through to P&L results',
      'Cost & Budget Concerns: unpredictable global freight markets affecting long-term financial planning',
      'Risk & Compliance: exposure to high-profile disruptions (geopolitical, climate, regulatory)',
      'Risk & Compliance: insufficient processes to safeguard against fraud or weak carrier vetting',
      'Technology & Data Gaps: lack of enterprise-wide freight visibility tools tied to executive dashboards',
      'Technology & Data Gaps: disparate systems that limit a single view of procurement impact',
      'Technology & Data Gaps: slow adoption of modern freight procurement technologies across regions',
      'Carrier & Supplier Management: difficulty balancing reliance on strategic partners with need for diversification',
      'Carrier & Supplier Management: limited visibility into supplier/carrier health and performance at board level',
      'Carrier & Supplier Management: tensions between cost-driven decisions and long-term relationship building',
      'Talent & Organizational Pressures: pressure on leadership to attract talent capable of modernizing freight procurement',
      'Talent & Organizational Pressures: need to foster cross-functional collaboration between finance, procurement, and operations'
    ],
    toneProfile: 'Be direct and decisive – cut to the chase with the big picture. Focus on outcomes and strategy – emphasize long-term vision, market position, and competitive edge. Use high-level language – avoid operational details unless directly tied to business growth or risk. Concise but compelling – short, impactful phrasing that reinforces urgency and direction.',
    keywords: ['strategic', 'enterprise', 'roi', 'scalability', 'executive', 'board', 'competitive advantage', 'enterprise-wide']
  },
  {
    id: 'coo',
    label: 'COO',
    department: 'Operations',
    seniority: 'C-Suite',
    painPoints: [
      'Strategic Challenges: translating the CEO\'s vision into executable operational strategies',
      'Strategic Challenges: balancing growth, efficiency, and agility in a fast-changing environment',
      'Strategic Challenges: scaling operations to support expansion while keeping costs under control',
      'Strategic Challenges: driving digital transformation without disrupting current operations',
      'Operational Efficiency: eliminating silos between business units to improve collaboration',
      'Operational Efficiency: streamlining processes and reducing inefficiencies in workflows',
      'Operational Efficiency: maintaining consistent performance across global operations',
      'Operational Efficiency: managing supply chain complexity, lead times, and logistics disruptions',
      'Operational Efficiency: balancing standardization with the need for local market flexibility',
      'Risk & Compliance: ensuring compliance with operational, legal, and industry regulations',
      'Risk & Compliance: managing operational risks, including supply chain disruptions, safety incidents, and business continuity',
      'Risk & Compliance: implementing effective crisis management and disaster recovery plans',
      'Risk & Compliance: maintaining quality assurance across diverse operations',
      'Data & Technology: gaining visibility into operational performance in real-time',
      'Data & Technology: integrating disparate systems (ERP, supply chain, HR, finance) into a cohesive platform',
      'Data & Technology: leveraging data analytics to drive decision-making and process improvements',
      'Data & Technology: adopting automation, AI, and robotics while managing workforce impact',
      'Data & Technology: balancing investment in new technology against ROI and adoption challenges',
      'Customer & Market Demands: meeting evolving customer expectations for speed, quality, and personalization',
      'Customer & Market Demands: ensuring customer experience aligns with operational capabilities',
      'Customer & Market Demands: responding quickly to competitor moves and market shifts',
      'Customer & Market Demands: balancing operational capacity with fluctuating demand',
      'Cost & Resource Management: managing rising operational costs (labor, logistics, raw materials, energy)',
      'Cost & Resource Management: optimizing resource allocation to achieve efficiency and growth',
      'Cost & Resource Management: reducing waste in production, logistics, and service delivery',
      'Cost & Resource Management: demonstrating operational value beyond cost cutting (e.g., resilience, agility)',
      'Leadership & Talent: attracting, developing, and retaining talent across multiple functions',
      'Leadership & Talent: leading cross-functional teams with diverse skills and priorities',
      'Leadership & Talent: building a culture of continuous improvement and accountability',
      'Leadership & Talent: overcoming resistance to operational change and transformation initiatives',
      'Leadership & Talent: preparing future leaders and succession planning for critical roles',
      'External Pressures: navigating geopolitical uncertainty, trade wars, and global instability',
      'External Pressures: managing environmental and sustainability expectations (green operations, carbon footprint reduction)',
      'External Pressures: coping with economic volatility, inflation, and fluctuating demand cycles',
      'External Pressures: maintaining competitive advantage in industries under rapid disruption'
    ],
    toneProfile: 'Be pragmatic and operational – focus on execution, efficiency, and scalability. Emphasize processes and performance metrics – KPIs, throughput, productivity. Balance detail with clarity – enough to explain how the system runs without bogging down. Results-oriented tone – show how initiatives translate into smoother operations.',
    keywords: ['operational', 'efficiency', 'standardization', 'execution', 'service', 'reliability', 'process', 'operations']
  },
  {
    id: 'cfo',
    label: 'CFO',
    department: 'Finance',
    seniority: 'C-Suite',
    painPoints: [
      'Strategic Challenges: balancing short-term financial performance with long-term growth strategy',
      'Strategic Challenges: driving digital transformation while maintaining financial discipline',
      'Strategic Challenges: navigating M&A (mergers & acquisitions), investments, and divestitures',
      'Financial Management: maintaining accurate forecasting in volatile markets',
      'Financial Management: managing cash flow and liquidity under uncertainty',
      'Financial Management: reducing costs without stifling innovation or growth',
      'Financial Management: optimizing capital allocation across competing priorities',
      'Risk & Compliance: keeping up with constantly changing regulations and tax laws',
      'Risk & Compliance: managing audit requirements and avoiding compliance penalties',
      'Risk & Compliance: monitoring financial risks, fraud, and cybersecurity threats',
      'Risk & Compliance: ensuring robust internal controls and governance structures',
      'Data & Technology: integrating disparate financial systems and data sources',
      'Data & Technology: gaining real-time visibility into company performance',
      'Data & Technology: turning financial data into actionable insights for decision-making',
      'Data & Technology: adopting AI/automation while managing associated risks',
      'Leadership & Talent: building and retaining a high-performing finance team',
      'Leadership & Talent: upscaling finance staff for analytics and digital tools',
      'Leadership & Talent: aligning finance with cross-functional business partners',
      'Leadership & Talent: managing organizational resistance to financial discipline',
      'External Pressures: meeting shareholder and board expectations for growth and profitability',
      'External Pressures: communicating effectively with investors, analysts, and stakeholders',
      'External Pressures: handling economic pressures such as inflation, interest rate changes, and currency fluctuations',
      'External Pressures: competing with industry peers in financial efficiency and reporting transparency'
    ],
    toneProfile: 'Be precise and evidence-based – numbers, trends, and cost-benefit clarity. Highlight financial impact – ROI, margins, savings, and risk exposure should lead. Be structured – organized, logical delivery with supporting metrics. Eliminate fluff – concise, data-heavy, and straight to financial implications.',
    keywords: ['financial', 'cost', 'optimization', 'performance', 'risk', 'roi', 'analytics', 'stakeholder']
  },
  {
    id: 'cpo',
    label: 'CPO (Chief Procurement Officer)',
    department: 'Operations',
    seniority: 'C-Suite',
    painPoints: [
      'Strategic Challenges: balancing long-term supplier partnerships with short-term cost savings',
      'Strategic Challenges: lack of alignment between procurement and other supply chain stakeholders',
      'Operational Pain Points: manual, time-consuming tendering processes',
      'Operational Pain Points: fragmented workflows across global procurement teams',
      'Operational Pain Points: high administrative burden in managing multiple carriers and brokers',
      'Cost & Budget Concerns: fluctuating freight costs complicating budgeting and savings targets',
      'Cost & Budget Concerns: limited ability to benchmark carrier pricing across markets',
      'Cost & Budget Concerns: challenges proving procurement-driven cost savings',
      'Risk & Compliance: inadequate processes for carrier onboarding and vetting',
      'Risk & Compliance: risk of relying on a narrow set of carriers during disruptions',
      'Technology & Data Gaps: lack of integration between procurement tools and logistics platforms',
      'Technology & Data Gaps: poor data availability for rate benchmarking and performance analysis',
      'Technology & Data Gaps: slow adoption of digital freight procurement solutions at scale',
      'Carrier & Supplier Management: difficulty balancing strategic carrier relationships with diversification needs',
      'Carrier & Supplier Management: limited visibility into carrier performance across all modes',
      'Carrier & Supplier Management: strain in negotiations during volatile capacity markets',
      'Talent & Organizational Pressures: shortage of procurement professionals with analytics and digital skills',
      'Talent & Organizational Pressures: pressure to deliver measurable savings and efficiency gains quickly',
      'Talent & Organizational Pressures: high turnover in procurement roles due to competitive market'
    ],
    toneProfile: 'Be strategic with operational depth – balance long-term goals with actionable next steps. Use comparative insights – benchmark performance, highlight best practices. Show resource allocation impact – budgets, technology adoption, vendor choices. Confident and professional – present clear recommendations backed by data.',
    keywords: ['procurement', 'sourcing', 'supplier', 'partnerships', 'cost', 'optimization', 'strategic', 'excellence']
  },
  {
    id: 'csco',
    label: 'CSCO (Chief Supply Chain Officer)',
    department: 'Operations',
    seniority: 'C-Suite',
    painPoints: [
      'Strategic Challenges: balancing supply chain resilience with procurement cost efficiency',
      'Strategic Challenges: ensuring freight procurement supports customer service expectations',
      'Strategic Challenges: aligning procurement with sustainability and decarbonization targets',
      'Operational Pain Points: fragmented freight procurement processes across regions and modes',
      'Operational Pain Points: lack of real-time shipment visibility impacting planning accuracy',
      'Operational Pain Points: disruptions requiring reactive, manual interventions',
      'Cost & Budget Concerns: unpredictable freight costs complicating supply chain cost optimization',
      'Cost & Budget Concerns: over-dependence on spot market driving unplanned budget spikes',
      'Cost & Budget Concerns: difficulty tying freight costs directly to product margins',
      'Risk & Compliance: high exposure to global disruptions (weather, strikes, geopolitics)',
      'Risk & Compliance: lack of standardized carrier vetting processes',
      'Risk & Compliance: vulnerability to reputational risk from non-compliant suppliers',
      'Technology & Data Gaps: disparate systems preventing end-to-end supply chain visibility',
      'Technology & Data Gaps: poor freight data limiting predictive planning capabilities',
      'Carrier & Supplier Management: tension between strategic partnerships and diversification for resilience',
      'Carrier & Supplier Management: limited visibility into carrier KPIs at the executive level',
      'Carrier & Supplier Management: difficulty maintaining service quality during cost negotiations',
      'Talent & Organizational Pressures: shortage of supply chain professionals with digital freight expertise',
      'Talent & Organizational Pressures: executive pressure to deliver resilient, cost-efficient supply chains',
      'Talent & Organizational Pressures: retention challenges due to high competition for top talent'
    ],
    toneProfile: 'Be comprehensive but focused – cover risks, dependencies, and performance drivers. Prioritize resilience and optimization – emphasize cost efficiency, reliability, and adaptability. Speak risk-aware – highlight disruptions, mitigations, and continuity planning. Analytical and structured – rely on data, forecasts, and supply chain models.',
    keywords: ['supply chain', 'resilience', 'customer', 'service', 'visibility', 'sustainability', 'optimization', 'strategy']
  },
  {
    id: 'owner_founder',
    label: 'Owner / Founder',
    department: 'Operations',
    seniority: 'C-Suite',
    painPoints: [
      'Strategic & Vision Challenges: balancing long-term vision with short-term execution pressures',
      'Strategic & Vision Challenges: difficulty in prioritizing opportunities vs. distractions',
      'Strategic & Vision Challenges: adapting business strategy to rapidly changing market conditions',
      'Strategic & Vision Challenges: fear of stagnation or being disrupted by competitors',
      'Financial & Resource Strain: securing consistent cash flow and funding',
      'Financial & Resource Strain: managing investor expectations while protecting company culture',
      'Financial & Resource Strain: budget allocation trade-offs between growth and sustainability',
      'People & Leadership Struggles: recruiting and retaining top talent in a competitive market',
      'People & Leadership Struggles: building and maintaining strong leadership teams',
      'People & Leadership Struggles: managing conflict among co-founders or senior leadership',
      'People & Leadership Struggles: balancing empathy with performance accountability',
      'Operational Burdens: wearing too many hats, especially in early stages',
      'Operational Burdens: lack of time to focus deeply due to constant context switching',
      'Operational Burdens: building scalable systems and processes without over-engineering',
      'Market & Growth Pressures: finding product-market fit (for early-stage founders)',
      'Market & Growth Pressures: sustaining growth without sacrificing quality or culture',
      'Market & Growth Pressures: differentiating in crowded, competitive markets',
      'Market & Growth Pressures: scaling sales and marketing efficiently',
      'Personal Stress & Wellbeing: high levels of stress, anxiety, and burnout',
      'Personal Stress & Wellbeing: loneliness in decision-making ("founder\'s isolation")',
      'Personal Stress & Wellbeing: difficulty maintaining work-life balance',
      'Personal Stress & Wellbeing: pressure of being the ultimate decision-maker',
      'Reputation & Legacy Concerns: protecting brand reputation in a hyper-visible digital era',
      'Reputation & Legacy Concerns: ensuring long-term impact beyond short-term wins',
      'Reputation & Legacy Concerns: concerns about succession planning and company legacy'
    ],
    toneProfile: 'Be visionary and inspiring – tie messages to purpose, mission, and the "why" behind the business. Personal and passionate – show genuine belief in the product, service, or company\'s journey. Focus on long-term value – sustainability, legacy, and reputation matter alongside financials. Balance detail with narrative – data is useful, but storytelling and conviction often resonate more. Relational tone – emphasize loyalty, culture, and alignment with the founder\'s values.',
    keywords: ['vision', 'growth', 'innovation', 'leadership', 'impact', 'founder', 'entrepreneur', 'strategy']
  },
  {
    id: 'operations_upper_management',
    label: 'Upper Management - Operations',
    department: 'Operations',
    seniority: 'Upper Management',
    painPoints: [
      'Strategic Challenges: balancing cost optimization with service reliability and customer expectations',
      'Strategic Challenges: limited visibility into end-to-end freight costs, making it hard to forecast and budget accurately',
      'Strategic Challenges: difficulty in maintaining flexibility while also committing to long-term carrier contracts',
      'Operational Pain Points: fragmented processes across regions, modes, and business units that hinder standardization',
      'Operational Pain Points: manual, time-consuming tendering and carrier selection processes',
      'Operational Pain Points: high administrative overhead due to managing multiple carriers, freight forwarders, and brokers',
      'Operational Pain Points: lack of real-time visibility into shipment status, exceptions, and disruptions',
      'Cost & Budget Concerns: volatile freight rates driven by fuel prices, geopolitical issues, and market cycles',
      'Cost & Budget Concerns: limited ability to benchmark carrier rates effectively due to inconsistent data',
      'Cost & Budget Concerns: difficulty in proving and tracking cost savings initiatives to executive stakeholders',
      'Cost & Budget Concerns: over-reliance on spot markets during capacity crunches, leading to unplanned cost spikes',
      'Risk & Compliance: exposure to supply chain disruptions (port congestion, strikes, geopolitical tensions, weather)',
      'Risk & Compliance: risk of carrier insolvency or underperformance affecting service levels',
      'Risk & Compliance: lack of standardized processes for supplier/carrier vetting and onboarding',
      'Technology & Data Gaps: disparate systems across transportation, procurement, and finance teams that don\'t integrate',
      'Technology & Data Gaps: poor quality or incomplete freight data limiting analytics and decision-making',
      'Technology & Data Gaps: difficulty adopting modern digital freight procurement tools at scale',
      'Technology & Data Gaps: resistance to change from teams accustomed to legacy/manual processes',
      'Carrier & Supplier Management: maintaining strong relationships with carriers while also pushing for lower rates',
      'Carrier & Supplier Management: balancing strategic carrier partnerships with the need for diversification to reduce dependency',
      'Carrier & Supplier Management: limited visibility into carrier performance metrics and KPIs across modes',
      'Carrier & Supplier Management: difficulty in negotiating fair contract terms during volatile capacity markets',
      'Talent & Organizational Pressures: shortage of supply chain professionals with advanced analytics and digital procurement skills',
      'Talent & Organizational Pressures: high expectations from executive leadership to deliver cost savings and efficiency improvements quickly',
      'Talent & Organizational Pressures: challenges in retaining top talent in a competitive supply chain labor market'
    ],
    toneProfile: 'Be strategic with operational depth – balance long-term goals with actionable next steps. Use comparative insights – benchmark performance, highlight best practices. Show resource allocation impact – budgets, technology adoption, vendor choices. Confident and professional – present clear recommendations backed by data.',
    keywords: ['operational', 'management', 'efficiency', 'team', 'process', 'departmental', 'leadership', 'productivity']
  },
  {
    id: 'operations_middle_management',
    label: 'Middle Management - Operations',
    department: 'Operations',
    seniority: 'Middle Management',
    painPoints: [
      'Execution & Day-to-Day Firefighting: constantly dealing with last-minute shipment changes, delays, and disruptions',
      'Execution & Day-to-Day Firefighting: difficulty reallocating loads when carriers reject tenders or fail to show',
      'Execution & Day-to-Day Firefighting: overwhelmed by daily problem-solving instead of focusing on proactive improvements',
      'Execution & Day-to-Day Firefighting: struggles managing exceptions in real time (detention, demurrage, customs issues)',
      'Carrier & Supplier Management: lack of leverage in negotiations with carriers compared to upper management',
      'Carrier & Supplier Management: managing compliance with contracted service levels and resolving disputes',
      'Carrier & Supplier Management: handling frequent communication breakdowns with carriers and brokers',
      'Carrier & Supplier Management: frustration with carriers not adhering to agreed pricing or capacity commitments',
      'Carrier & Supplier Management: struggles to maintain balanced routing guides while keeping carriers engaged',
      'Process Inefficiencies: heavy reliance on manual tools (spreadsheets, email) for bid collection and analysis',
      'Process Inefficiencies: limited access to procurement automation tools that leadership might want but hasn\'t yet invested in',
      'Process Inefficiencies: redundant data entry across procurement, TMS, and ERP systems',
      'Process Inefficiencies: long approval chains slowing down tactical decisions',
      'Data & Visibility Limitations: insufficient visibility into shipment status after awarding freight',
      'Data & Visibility Limitations: lack of timely reporting for KPIs like carrier performance, lane costs, or service failures',
      'Data & Visibility Limitations: data scattered across multiple systems, making it hard to analyze performance',
      'Data & Visibility Limitations: struggles to provide upper management with accurate, real-time insights',
      'Cost & Budget Pressures: pressure to cut costs without sacrificing service reliability',
      'Cost & Budget Pressures: limited authority to adjust pricing or make exceptions without escalation',
      'Cost & Budget Pressures: constantly balancing budget compliance with operational needs',
      'Cost & Budget Pressures: difficulty justifying small budget overruns tied to unforeseen surcharges or accessorials',
      'Stakeholder Coordination: managing expectations from warehouse, operations, and sales teams for on-time shipments',
      'Stakeholder Coordination: pressure from leadership for cost savings while front-line teams demand faster turnaround',
      'Stakeholder Coordination: conflict resolution between internal stakeholders and external carriers',
      'Stakeholder Coordination: juggling multiple priorities: service reliability, budget compliance, and customer satisfaction',
      'Talent & Team Management: shortage of staff or over-reliance on a small team to handle large procurement workloads',
      'Talent & Team Management: difficulty training junior staff on complex sourcing and negotiation tasks',
      'Talent & Team Management: high employee turnover increasing workload on remaining team members',
      'Talent & Team Management: morale challenges due to repetitive manual work and constant firefighting',
      'Technology & Tools: frustration with outdated procurement and logistics systems',
      'Technology & Tools: lack of integration between procurement platforms, TMS, and visibility tools',
      'Technology & Tools: limited influence on IT/tooling decisions made at higher levels',
      'Technology & Tools: struggles to adopt new digital platforms while keeping up with daily workload',
      'Compliance & Risk: ensuring adherence to corporate procurement policies during sourcing',
      'Compliance & Risk: navigating carrier insurance, safety records, and regulatory compliance',
      'Compliance & Risk: managing the risk of penalties from late deliveries or missed SLAs',
      'Compliance & Risk: difficulty aligning sourcing practices with corporate sustainability initiatives'
    ],
    toneProfile: 'Be actionable and tactical – focus on "what needs to happen next." Provide clarity and guidance – simplify priorities for their teams. Problem-solving tone – address bottlenecks, performance issues, and team management. Collaborative but firm – engage them in decisions while setting clear expectations.',
    keywords: ['practical', 'hands-on', 'execution', 'team', 'daily', 'coordination', 'implementation', 'management']
  },
  {
    id: 'first_logistics_manager',
    label: 'First-ever Logistics Manager',
    department: 'Operations',
    seniority: 'Middle Management',
    painPoints: [
      'Building from Scratch: establishing processes and systems where none existed before',
      'Building from Scratch: creating logistics infrastructure for a growing company',
      'Building from Scratch: defining roles and responsibilities for the new logistics function',
      'Building from Scratch: setting up carrier relationships and vendor management processes',
      'Resource Constraints: limited budget for logistics technology and tools',
      'Resource Constraints: need to prove ROI of logistics investments to leadership',
      'Resource Constraints: balancing cost control with service quality as the company scales',
      'Learning Curve: understanding best practices in logistics and supply chain management',
      'Learning Curve: navigating different transportation modes and carrier options',
      'Learning Curve: learning to negotiate with carriers and manage contracts',
      'Technology Gaps: lack of integrated systems for freight procurement and tracking',
      'Technology Gaps: need for visibility tools to monitor shipments and performance',
      'Technology Gaps: manual processes that don\'t scale with company growth',
      'Team Building: hiring and training logistics staff as the function grows',
      'Team Building: establishing processes for cross-functional collaboration',
      'Team Building: creating performance metrics and KPIs for the logistics function',
      'Strategic Alignment: aligning logistics strategy with overall business growth plans',
      'Strategic Alignment: balancing cost optimization with customer service requirements',
      'Strategic Alignment: building scalable processes that can handle future growth',
      'External Pressures: managing increasing shipping volumes and complexity',
      'External Pressures: dealing with supply chain disruptions and market volatility',
      'External Pressures: keeping up with industry best practices and technology trends'
    ],
    toneProfile: 'Be supportive and educational – acknowledge they\'re building something new. Focus on practical, actionable solutions – show how to establish processes and systems. Emphasize growth and scalability – help them build for the future. Use encouraging language – recognize the challenge and opportunity of creating something from scratch.',
    keywords: ['logistics', 'first-ever', 'startup', 'growing', 'building', 'establishing', 'processes', 'systems', 'infrastructure', 'scalable', 'foundation']
  },
  {
    id: 'operations_entry_level',
    label: 'Entry Level - Operations',
    department: 'Operations',
    seniority: 'Entry Level',
    painPoints: [
      'Operational & Process-Related Pain Points: manual, time-consuming procurement processes with limited automation',
      'Operational & Process-Related Pain Points: difficulty consolidating data across multiple systems (TMS, ERP, spreadsheets)',
      'Operational & Process-Related Pain Points: frequent misalignment between procurement, operations, and finance teams',
      'Operational & Process-Related Pain Points: high administrative workload (rate requests, tender management, contract tracking)',
      'Operational & Process-Related Pain Points: difficulty maintaining accurate shipment and freight cost data',
      'Market & Supplier Challenges: volatility in freight rates due to fuel costs, capacity fluctuations, and global disruptions',
      'Market & Supplier Challenges: limited visibility into carrier performance and reliability',
      'Market & Supplier Challenges: challenges in building strong supplier/carrier relationships at a non-strategic level',
      'Market & Supplier Challenges: difficulty benchmarking rates to ensure competitiveness',
      'Market & Supplier Challenges: limited negotiation power if not a large shipper',
      'Cost & Budget Constraints: pressure to cut costs while ensuring service reliability',
      'Cost & Budget Constraints: difficulty balancing lowest-cost bids with service quality and risk',
      'Cost & Budget Constraints: inability to predict or forecast freight spend accurately',
      'Cost & Budget Constraints: hidden costs (detention, demurrage, surcharges) eroding budgets',
      'Data & Visibility Issues: fragmented data leading to poor real-time visibility into shipments and spend',
      'Data & Visibility Issues: lack of standardized KPIs and reporting tools for performance tracking',
      'Data & Visibility Issues: inconsistent data quality across internal and external systems',
      'Data & Visibility Issues: difficulty using analytics to support decision-making',
      'Compliance & Risk: struggles to ensure compliance with contracts, regulations, and trade requirements',
      'Compliance & Risk: limited bandwidth to monitor risk factors (e.g., geopolitical, port strikes, weather disruptions)',
      'Compliance & Risk: difficulty auditing freight invoices and ensuring accuracy',
      'Technology Limitations: reliance on outdated tools (email, Excel) for procurement and bidding',
      'Technology Limitations: limited adoption of digital freight platforms or automation technologies',
      'Technology Limitations: steep learning curves when adopting new procurement software',
      'Technology Limitations: integration issues between procurement tools and logistics systems',
      'Collaboration & Communication: frequent miscommunication between procurement and operations teams',
      'Collaboration & Communication: lack of transparency with carriers regarding capacity, rates, and performance',
      'Collaboration & Communication: challenges in aligning procurement strategies with broader supply chain goals',
      'Collaboration & Communication: difficulty escalating issues internally when lacking decision-making authority',
      'Career & Role-Specific Pain Points: limited visibility of their work\'s impact on overall supply chain performance',
      'Career & Role-Specific Pain Points: feeling undervalued as procurement is often seen as a "cost center"',
      'Career & Role-Specific Pain Points: lack of clear career progression paths in freight procurement',
      'Career & Role-Specific Pain Points: high stress due to constant firefighting (spot buys, urgent shipments, last-minute changes)'
    ],
    toneProfile: 'Be instructional and clear – explain expectations and next steps in detail. Encourage learning – break down processes and why they matter. Supportive tone – constructive feedback with focus on skill development. Detail-oriented – emphasize accuracy, process adherence, and reporting quality.',
    keywords: ['learning', 'development', 'growth', 'support', 'education', 'mentorship', 'career', 'skills']
  },
  {
    id: 'operations_intern',
    label: 'Intern - Operations',
    department: 'Operations',
    seniority: 'Intern',
    painPoints: [
      'Understanding basic freight and logistics concepts',
      'Learning company processes and systems',
      'Managing administrative tasks and data entry',
      'Understanding different transportation modes',
      'Learning to communicate with carriers and customers',
      'Understanding basic cost and pricing concepts',
      'Managing time and meeting deadlines',
      'Learning to use company software and tools',
      'Understanding basic compliance requirements',
      'Learning to work in a team environment',
      'Understanding the role of technology in logistics',
      'Learning to analyze basic performance data',
      'Understanding customer service principles',
      'Learning to manage multiple tasks simultaneously',
      'Understanding the impact of external factors',
      'Learning to work with different departments',
      'Understanding basic negotiation concepts',
      'Learning to identify process improvements',
      'Understanding the importance of accuracy and attention to detail',
      'Learning to adapt to changing priorities and requirements'
    ],
    toneProfile: 'Be patient and explanatory – over-communicate to ensure understanding. Keep it simple and structured – clear tasks, step-by-step guidance. Encouraging and mentoring – foster curiosity and confidence. Positive and approachable – tone should reduce intimidation and promote engagement.',
    keywords: ['learning', 'exploration', 'discovery', 'mentorship', 'growth', 'experience', 'development', 'opportunity']
  },
  // Finance Department
  {
    id: 'finance_upper_management',
    label: 'Upper Management - Finance',
    department: 'Finance',
    seniority: 'Upper Management',
    painPoints: [
      'Strategic & Financial Pressure: balancing short-term cost-cutting with long-term investment and growth strategies',
      'Strategic & Financial Pressure: increasing pressure from boards and investors for predictable financial performance',
      'Strategic & Financial Pressure: difficulty in forecasting accurately amid economic volatility, currency fluctuations, and market uncertainty',
      'Strategic & Financial Pressure: pressure to provide actionable insights beyond reporting (acting as a strategic partner vs. back-office)',
      'Operational Inefficiencies: reliance on outdated ERP/financial systems that require manual data reconciliation',
      'Operational Inefficiencies: complex, time-consuming month-end and quarter-end close processes',
      'Operational Inefficiencies: inconsistent processes across regions/business units, slowing down consolidation',
      'Data & Reporting Challenges: lack of real-time visibility into company supply chain health across operations',
      'Data & Reporting Challenges: struggles with data quality, accuracy, and consistency when pulling from multiple systems',
      'Data & Reporting Challenges: limited automation in reporting, leading to heavy reliance on spreadsheets',
      'Data & Reporting Challenges: difficulty delivering timely insights to executives due to manual reporting cycles',
      'Data & Reporting Challenges: regulatory reporting requirements that demand higher precision and audit-ability',
      'Technology Limitations: difficulty justifying ROI on finance digital transformation projects',
      'Technology Limitations: limited integration between ERP, BI, and planning systems',
      'Technology Limitations: struggles with implementing advanced analytics, AI, or automation due to data silos',
      'Talent & Organizational Issues: gaps in advanced analytics, automation, and digital finance capabilities among staff',
      'Talent & Organizational Issues: misalignment between finance priorities and operational/business unit leaders'
    ],
    toneProfile: 'Be strategic with operational depth – balance long-term goals with actionable next steps. Use comparative insights – benchmark performance, highlight best practices. Show resource allocation impact – budgets, technology adoption, vendor choices. Confident and professional – present clear recommendations backed by data.',
    keywords: ['financial', 'management', 'departmental', 'controls', 'team', 'leadership', 'performance', 'planning']
  },
  {
    id: 'finance_middle_management',
    label: 'Middle Management - Finance',
    department: 'Finance',
    seniority: 'Middle Management',
    painPoints: [
      'Cost Control & Budget Management: freight spend is highly variable and difficult to forecast due to rate volatility',
      'Cost Control & Budget Management: hidden surcharges (fuel, accessorials, detention, demurrage) make budgeting unpredictable',
      'Cost Control & Budget Management: inability to accurately allocate transportation costs to specific products, regions, or business units',
      'Cost Control & Budget Management: difficulty validating that negotiated carrier rates are actually being applied in invoices',
      'Cost Control & Budget Management: pressure to reduce logistics costs while balancing service-level requirements',
      'Freight Audit & Payment Challenges: manual invoice reconciliation leading to errors and delays',
      'Freight Audit & Payment Challenges: high volume of freight invoices creates administrative burden',
      'Freight Audit & Payment Challenges: difficulty matching invoices to contracts, shipments, and POs',
      'Freight Audit & Payment Challenges: carrier overbilling or duplicate charges slipping through without proper audit controls',
      'Data & Reporting Limitations: limited visibility into total landed cost and how freight affects product margins',
      'Data & Reporting Limitations: inconsistent data across procurement, logistics, and finance systems',
      'Data & Reporting Limitations: difficulty producing accurate financial reports for leadership or regulators',
      'Data & Reporting Limitations: lack of standardized KPIs to measure cost efficiency of procurement decisions',
      'Data & Reporting Limitations: struggles to provide real-time reporting to support operational decision-making',
      'Risk & Compliance: exposure to financial risks from fuel price spikes, capacity shortages, or tariff changes',
      'Cross-Department Coordination: misalignment between finance, procurement, and operations on cost-saving initiatives',
      'Cross-Department Coordination: difficulty validating savings claimed by procurement against actual financial outcomes',
      'Cross-Department Coordination: pressure from CFO/board to demonstrate ROI of procurement projects',
      'Cross-Department Coordination: tension between finance\'s need for strict controls and operations\' need for agility',
      'Cross-Department Coordination: lack of clear accountability for freight cost overruns between departments',
      'Technology & Systems Gaps: reliance on outdated freight payment systems or spreadsheets',
      'Technology & Systems Gaps: poor integration between TMS, ERP, and financial systems',
      'Technology & Systems Gaps: difficulty adopting modern spend analytics tools without disrupting existing processes',
      'Technology & Systems Gaps: high IT/security hurdles to integrate external freight platforms with finance systems',
      'Strategic Pressures: increasing demand to make freight spend more predictable for earnings guidance',
      'Strategic Pressures: difficulty balancing short-term cost savings with long-term supply chain resilience',
      'Strategic Pressures: pressure to identify cost-saving opportunities in freight without undermining service quality',
      'Strategic Pressures: challenges in quantifying the financial impact of disruptions (e.g., port congestion, strikes)'
    ],
    toneProfile: 'Be actionable and tactical – focus on "what needs to happen next." Provide clarity and guidance – simplify priorities for their teams. Problem-solving tone – address bottlenecks, performance issues, and team management. Collaborative but firm – engage them in decisions while setting clear expectations.',
    keywords: ['financial', 'analysis', 'practical', 'execution', 'team', 'coordination', 'management', 'solutions']
  },
  {
    id: 'finance_entry_level',
    label: 'Entry Level - Finance',
    department: 'Finance',
    seniority: 'Entry Level',
    painPoints: [
      'Operational & Process-Related Pain Points: heavy reliance on manual processes (Excel spreadsheets, email approvals, manual reconciliations)',
      'Operational & Process-Related Pain Points: time-consuming month-end and quarter-end closing cycles',
      'Operational & Process-Related Pain Points: difficulty consolidating financial data across multiple systems (ERP, procurement, logistics platforms)',
      'Operational & Process-Related Pain Points: lack of standardization in processes across business units or regions',
      'Operational & Process-Related Pain Points: high volume of repetitive tasks (invoice matching, expense tracking, reporting)',
      'Cost & Budget Management: limited visibility into actual vs. forecasted freight and procurement spend',
      'Cost & Budget Management: difficulty controlling costs when unexpected surcharges, detention, or demurrage occur',
      'Cost & Budget Management: budget overruns due to poor communication between operations and finance teams',
      'Cost & Budget Management: lack of granular cost allocation by lane, product, or business unit',
      'Cost & Budget Management: difficulty ensuring cost savings initiatives in procurement are actually realized and measurable',
      'Data & Reporting Challenges: fragmented systems leading to inconsistent data quality',
      'Data & Reporting Challenges: inability to generate real-time insights or dashboards for stakeholders',
      'Data & Reporting Challenges: long lead times to produce accurate reports for management',
      'Data & Reporting Challenges: difficulty tracking KPIs that connect financial metrics with supply chain performance',
      'Data & Reporting Challenges: struggles to translate complex financial data into actionable business insights for non-finance teams',
      'Compliance & Risk: difficulty auditing freight invoices and spotting discrepancies',
      'Compliance & Risk: risk exposure due to lack of oversight on vendor payments and contracts',
      'Technology Limitations: ERP systems that are outdated or poorly integrated with procurement/logistics platforms',
      'Technology Limitations: lack of automation for accounts payable and receivable processes',
      'Technology Limitations: difficulty implementing new finance tools due to steep learning curves or IT dependency',
      'Technology Limitations: limited ability to leverage predictive analytics for cost forecasting and scenario planning',
      'Collaboration & Communication: misalignment between finance, procurement, and operations on budgeting and cost drivers',
      'Collaboration & Communication: friction with non-financial stakeholders who may not understand finance constraints',
      'Collaboration & Communication: difficulty communicating the financial impact of supply chain disruptions to leadership',
      'Collaboration & Communication: slow approval cycles due to lack of clarity in financial authority levels',
      'Career & Role-Specific Pain Points: entry-level analysts bogged down with repetitive transactional work and limited exposure to strategic tasks',
      'Career & Role-Specific Pain Points: senior specialists/individual contributors struggling with balancing tactical reporting and higher-level analysis',
      'Career & Role-Specific Pain Points: lack of career progression or development opportunities in finance compared to other functions',
      'Career & Role-Specific Pain Points: feeling like "gatekeepers" rather than strategic partners, reducing job satisfaction',
      'Career & Role-Specific Pain Points: stress from constant deadlines and last-minute requests for data from leadership'
    ],
    toneProfile: 'Be instructional and clear – explain expectations and next steps in detail. Encourage learning – break down processes and why they matter. Supportive tone – constructive feedback with focus on skill development. Detail-oriented – emphasize accuracy, process adherence, and reporting quality.',
    keywords: ['financial', 'learning', 'development', 'growth', 'education', 'skills', 'professional', 'support']
  },
  {
    id: 'finance_intern',
    label: 'Intern - Finance',
    department: 'Finance',
    seniority: 'Intern',
    painPoints: [
      'Understanding basic financial concepts',
      'Learning company financial processes',
      'Managing financial data entry and reporting',
      'Understanding financial regulations and compliance',
      'Learning to use financial systems and tools',
      'Understanding financial performance metrics',
      'Learning to analyze basic financial data',
      'Understanding financial risk management',
      'Managing financial documentation and records',
      'Learning to work with financial stakeholders',
      'Understanding financial planning and forecasting',
      'Learning to identify financial opportunities',
      'Understanding financial controls and processes',
      'Learning to manage financial projects',
      'Understanding financial reporting requirements',
      'Learning to work with different departments',
      'Understanding financial technology and tools',
      'Learning to manage financial deadlines',
      'Understanding financial compliance requirements',
      'Learning to adapt to changing financial requirements'
    ],
    toneProfile: 'Be patient and explanatory – over-communicate to ensure understanding. Keep it simple and structured – clear tasks, step-by-step guidance. Encouraging and mentoring – foster curiosity and confidence. Positive and approachable – tone should reduce intimidation and promote engagement.',
    keywords: ['financial', 'learning', 'exploration', 'discovery', 'development', 'professional', 'growth', 'opportunity']
  },
  
  // Logistics Department
  {
    id: 'logistics_upper_management',
    label: 'Upper Management - Logistics',
    department: 'Logistics',
    seniority: 'Upper Management',
    painPoints: [
      'Strategic Challenges: balancing cost optimization with service reliability and customer expectations',
      'Strategic Challenges: limited visibility into end-to-end logistics operations, making it hard to forecast and optimize performance',
      'Strategic Challenges: difficulty in maintaining flexibility while also committing to long-term logistics partnerships',
      'Operational Pain Points: fragmented processes across regions, modes, and business units that hinder standardization',
      'Operational Pain Points: manual, time-consuming logistics planning and execution processes',
      'Operational Pain Points: high administrative overhead due to managing multiple logistics providers, 3PLs, and carriers',
      'Operational Pain Points: lack of real-time visibility into shipment status, exceptions, and disruptions',
      'Cost & Budget Concerns: volatile logistics costs driven by fuel prices, capacity constraints, and market cycles',
      'Cost & Budget Concerns: limited ability to benchmark logistics rates effectively due to inconsistent data',
      'Cost & Budget Concerns: difficulty in proving and tracking cost savings initiatives to executive stakeholders',
      'Cost & Budget Concerns: over-reliance on spot markets during capacity crunches, leading to unplanned cost spikes',
      'Risk & Compliance: exposure to supply chain disruptions (port congestion, strikes, geopolitical tensions, weather)',
      'Risk & Compliance: risk of logistics provider insolvency or underperformance affecting service levels',
      'Risk & Compliance: lack of standardized processes for logistics provider vetting and onboarding',
      'Technology & Data Gaps: disparate systems across transportation, warehousing, and logistics teams that don\'t integrate',
      'Technology & Data Gaps: poor quality or incomplete logistics data limiting analytics and decision-making',
      'Technology & Data Gaps: difficulty adopting modern digital logistics management tools at scale',
      'Technology & Data Gaps: resistance to change from teams accustomed to legacy/manual processes',
      'Provider & Partner Management: maintaining strong relationships with logistics providers while also pushing for lower rates',
      'Provider & Partner Management: balancing strategic logistics partnerships with the need for diversification to reduce dependency',
      'Provider & Partner Management: limited visibility into logistics provider performance metrics and KPIs across modes',
      'Provider & Partner Management: difficulty in negotiating fair contract terms during volatile capacity markets',
      'Talent & Organizational Pressures: shortage of logistics professionals with advanced analytics and digital logistics skills',
      'Talent & Organizational Pressures: high expectations from executive leadership to deliver cost savings and efficiency improvements quickly',
      'Talent & Organizational Pressures: challenges in retaining top talent in a competitive logistics labor market'
    ],
    toneProfile: 'Be strategic with operational depth – balance long-term goals with actionable next steps. Use comparative insights – benchmark performance, highlight best practices. Show resource allocation impact – budgets, technology adoption, vendor choices. Confident and professional – present clear recommendations backed by data.',
    keywords: ['logistics', 'management', 'efficiency', 'team', 'process', 'departmental', 'leadership', 'productivity']
  },
  {
    id: 'logistics_middle_management',
    label: 'Middle Management - Logistics',
    department: 'Logistics',
    seniority: 'Middle Management',
    painPoints: [
      'Execution & Day-to-Day Firefighting: constantly dealing with last-minute logistics changes, delays, and disruptions',
      'Execution & Day-to-Day Firefighting: difficulty reallocating shipments when logistics providers reject loads or fail to show',
      'Execution & Day-to-Day Firefighting: overwhelmed by daily problem-solving instead of focusing on proactive improvements',
      'Execution & Day-to-Day Firefighting: struggles managing exceptions in real time (detention, demurrage, customs issues)',
      'Provider & Partner Management: lack of leverage in negotiations with logistics providers compared to upper management',
      'Provider & Partner Management: managing compliance with contracted service levels and resolving disputes',
      'Provider & Partner Management: handling frequent communication breakdowns with logistics providers and 3PLs',
      'Provider & Partner Management: frustration with providers not adhering to agreed pricing or capacity commitments',
      'Provider & Partner Management: struggles to maintain balanced routing guides while keeping providers engaged',
      'Process Inefficiencies: heavy reliance on manual tools (spreadsheets, email) for logistics planning and analysis',
      'Process Inefficiencies: limited access to logistics automation tools that leadership might want but hasn\'t yet invested in',
      'Process Inefficiencies: redundant data entry across logistics, TMS, and ERP systems',
      'Process Inefficiencies: long approval chains slowing down tactical decisions',
      'Data & Visibility Limitations: insufficient visibility into shipment status after awarding logistics',
      'Data & Visibility Limitations: lack of timely reporting for KPIs like provider performance, lane costs, or service failures',
      'Data & Visibility Limitations: data scattered across multiple systems, making it hard to analyze performance',
      'Data & Visibility Limitations: struggles to provide upper management with accurate, real-time insights',
      'Cost & Budget Pressures: pressure to cut costs without sacrificing service reliability',
      'Cost & Budget Pressures: limited authority to adjust pricing or make exceptions without escalation',
      'Cost & Budget Pressures: constantly balancing budget compliance with operational needs',
      'Cost & Budget Pressures: difficulty justifying small budget overruns tied to unforeseen surcharges or accessorials',
      'Stakeholder Coordination: managing expectations from warehouse, operations, and sales teams for on-time shipments',
      'Stakeholder Coordination: pressure from leadership for cost savings while front-line teams demand faster turnaround',
      'Stakeholder Coordination: conflict resolution between internal stakeholders and external logistics providers',
      'Stakeholder Coordination: juggling multiple priorities: service reliability, budget compliance, and customer satisfaction',
      'Talent & Team Management: shortage of staff or over-reliance on a small team to handle large logistics workloads',
      'Talent & Team Management: difficulty training junior staff on complex logistics planning and execution tasks',
      'Talent & Team Management: high employee turnover increasing workload on remaining team members',
      'Talent & Team Management: morale challenges due to repetitive manual work and constant firefighting',
      'Technology & Tools: frustration with outdated logistics and transportation management systems',
      'Technology & Tools: lack of integration between logistics platforms, TMS, and visibility tools',
      'Technology & Tools: limited influence on IT/tooling decisions made at higher levels',
      'Technology & Tools: struggles to adopt new digital platforms while keeping up with daily workload',
      'Compliance & Risk: ensuring adherence to corporate logistics policies during planning',
      'Compliance & Risk: navigating provider insurance, safety records, and regulatory compliance',
      'Compliance & Risk: managing the risk of penalties from late deliveries or missed SLAs',
      'Compliance & Risk: difficulty aligning logistics practices with corporate sustainability initiatives'
    ],
    toneProfile: 'Be actionable and tactical – focus on "what needs to happen next." Provide clarity and guidance – simplify priorities for their teams. Problem-solving tone – address bottlenecks, performance issues, and team management. Collaborative but firm – engage them in decisions while setting clear expectations.',
    keywords: ['logistics', 'practical', 'hands-on', 'execution', 'team', 'daily', 'coordination', 'implementation', 'management']
  },
  {
    id: 'logistics_entry_level',
    label: 'Entry Level - Logistics',
    department: 'Logistics',
    seniority: 'Entry Level',
    painPoints: [
      'Operational & Process-Related Pain Points: manual, time-consuming logistics processes with limited automation',
      'Operational & Process-Related Pain Points: difficulty consolidating data across multiple systems (TMS, ERP, spreadsheets)',
      'Operational & Process-Related Pain Points: frequent misalignment between logistics, operations, and finance teams',
      'Operational & Process-Related Pain Points: high administrative workload (rate requests, logistics planning, contract tracking)',
      'Operational & Process-Related Pain Points: difficulty maintaining accurate shipment and logistics cost data',
      'Market & Provider Challenges: volatility in logistics rates due to fuel costs, capacity fluctuations, and global disruptions',
      'Market & Provider Challenges: limited visibility into logistics provider performance and reliability',
      'Market & Provider Challenges: challenges in building strong provider relationships at a non-strategic level',
      'Market & Provider Challenges: difficulty benchmarking rates to ensure competitiveness',
      'Market & Provider Challenges: limited negotiation power if not a large shipper',
      'Cost & Budget Constraints: pressure to cut costs while ensuring service reliability',
      'Cost & Budget Constraints: difficulty balancing lowest-cost bids with service quality and risk',
      'Cost & Budget Constraints: inability to predict or forecast logistics spend accurately',
      'Cost & Budget Constraints: hidden costs (detention, demurrage, surcharges) eroding budgets',
      'Data & Visibility Issues: fragmented data leading to poor real-time visibility into shipments and spend',
      'Data & Visibility Issues: lack of standardized KPIs and reporting tools for performance tracking',
      'Data & Visibility Issues: inconsistent data quality across internal and external systems',
      'Data & Visibility Issues: difficulty using analytics to support decision-making',
      'Compliance & Risk: struggles to ensure compliance with contracts, regulations, and trade requirements',
      'Compliance & Risk: limited bandwidth to monitor risk factors (e.g., geopolitical, port strikes, weather disruptions)',
      'Compliance & Risk: difficulty auditing logistics invoices and ensuring accuracy',
      'Technology Limitations: reliance on outdated tools (email, Excel) for logistics planning and execution',
      'Technology Limitations: limited adoption of digital logistics platforms or automation technologies',
      'Technology Limitations: steep learning curves when adopting new logistics software',
      'Technology Limitations: integration issues between logistics tools and transportation systems',
      'Collaboration & Communication: frequent miscommunication between logistics and operations teams',
      'Collaboration & Communication: lack of transparency with providers regarding capacity, rates, and performance',
      'Collaboration & Communication: challenges in aligning logistics strategies with broader supply chain goals',
      'Collaboration & Communication: difficulty escalating issues internally when lacking decision-making authority',
      'Career & Role-Specific Pain Points: limited visibility of their work\'s impact on overall logistics performance',
      'Career & Role-Specific Pain Points: feeling undervalued as logistics is often seen as a "cost center"',
      'Career & Role-Specific Pain Points: lack of clear career progression paths in logistics management',
      'Career & Role-Specific Pain Points: high stress due to constant firefighting (spot buys, urgent shipments, last-minute changes)'
    ],
    toneProfile: 'Be instructional and clear – explain expectations and next steps in detail. Encourage learning – break down processes and why they matter. Supportive tone – constructive feedback with focus on skill development. Detail-oriented – emphasize accuracy, process adherence, and reporting quality.',
    keywords: ['logistics', 'learning', 'development', 'growth', 'support', 'education', 'mentorship', 'career', 'skills']
  },
  {
    id: 'logistics_intern',
    label: 'Intern - Logistics',
    department: 'Logistics',
    seniority: 'Intern',
    painPoints: [
      'Understanding basic logistics and transportation concepts',
      'Learning company logistics processes and systems',
      'Managing administrative tasks and data entry',
      'Understanding different transportation modes and logistics networks',
      'Learning to communicate with logistics providers and customers',
      'Understanding basic cost and pricing concepts in logistics',
      'Managing time and meeting deadlines',
      'Learning to use company logistics software and tools',
      'Understanding basic compliance requirements',
      'Learning to work in a team environment',
      'Understanding the role of technology in logistics',
      'Learning to analyze basic logistics performance data',
      'Understanding customer service principles in logistics',
      'Learning to manage multiple tasks simultaneously',
      'Understanding the impact of external factors on logistics',
      'Learning to work with different departments',
      'Understanding basic negotiation concepts',
      'Learning to identify process improvements',
      'Understanding the importance of accuracy and attention to detail',
      'Learning to adapt to changing priorities and requirements'
    ],
    toneProfile: 'Be patient and explanatory – over-communicate to ensure understanding. Keep it simple and structured – clear tasks, step-by-step guidance. Encouraging and mentoring – foster curiosity and confidence. Positive and approachable – tone should reduce intimidation and promote engagement.',
    keywords: ['logistics', 'learning', 'exploration', 'discovery', 'mentorship', 'growth', 'experience', 'development', 'opportunity']
  },
  
  // Supply Chain Department
  {
    id: 'supply_chain_upper_management',
    label: 'Upper Management - Supply Chain',
    department: 'Supply Chain',
    seniority: 'Upper Management',
    painPoints: [
      'Strategic Challenges: balancing supply chain resilience with cost efficiency and customer service expectations',
      'Strategic Challenges: limited end-to-end visibility across the entire supply chain, making it hard to optimize and forecast',
      'Strategic Challenges: difficulty in maintaining supply chain flexibility while also committing to long-term partnerships',
      'Operational Pain Points: fragmented processes across suppliers, manufacturers, distributors, and retailers',
      'Operational Pain Points: manual, time-consuming supply chain planning and coordination processes',
      'Operational Pain Points: high administrative overhead due to managing multiple supply chain partners and systems',
      'Operational Pain Points: lack of real-time visibility into supply chain status, exceptions, and disruptions',
      'Cost & Budget Concerns: volatile supply chain costs driven by raw materials, transportation, and market cycles',
      'Cost & Budget Concerns: limited ability to benchmark supply chain performance effectively due to inconsistent data',
      'Cost & Budget Concerns: difficulty in proving and tracking supply chain optimization initiatives to executive stakeholders',
      'Cost & Budget Concerns: over-reliance on reactive solutions during supply chain disruptions, leading to unplanned cost spikes',
      'Risk & Compliance: exposure to supply chain disruptions (supplier issues, transportation delays, geopolitical tensions, weather)',
      'Risk & Compliance: risk of supply chain partner insolvency or underperformance affecting service levels',
      'Risk & Compliance: lack of standardized processes for supply chain partner vetting and onboarding',
      'Technology & Data Gaps: disparate systems across procurement, manufacturing, logistics, and sales teams that don\'t integrate',
      'Technology & Data Gaps: poor quality or incomplete supply chain data limiting analytics and decision-making',
      'Technology & Data Gaps: difficulty adopting modern digital supply chain management tools at scale',
      'Technology & Data Gaps: resistance to change from teams accustomed to legacy/manual processes',
      'Partner & Supplier Management: maintaining strong relationships with supply chain partners while also pushing for better terms',
      'Partner & Supplier Management: balancing strategic supply chain partnerships with the need for diversification to reduce dependency',
      'Partner & Supplier Management: limited visibility into supply chain partner performance metrics and KPIs across the network',
      'Partner & Supplier Management: difficulty in negotiating fair terms during volatile market conditions',
      'Talent & Organizational Pressures: shortage of supply chain professionals with advanced analytics and digital supply chain skills',
      'Talent & Organizational Pressures: high expectations from executive leadership to deliver cost savings and efficiency improvements quickly',
      'Talent & Organizational Pressures: challenges in retaining top talent in a competitive supply chain labor market'
    ],
    toneProfile: 'Be strategic with operational depth – balance long-term goals with actionable next steps. Use comparative insights – benchmark performance, highlight best practices. Show resource allocation impact – budgets, technology adoption, partner choices. Confident and professional – present clear recommendations backed by data.',
    keywords: ['supply chain', 'management', 'efficiency', 'team', 'process', 'departmental', 'leadership', 'productivity']
  },
  {
    id: 'supply_chain_middle_management',
    label: 'Middle Management - Supply Chain',
    department: 'Supply Chain',
    seniority: 'Middle Management',
    painPoints: [
      'Execution & Day-to-Day Firefighting: constantly dealing with last-minute supply chain changes, delays, and disruptions',
      'Execution & Day-to-Day Firefighting: difficulty reallocating resources when supply chain partners fail to deliver',
      'Execution & Day-to-Day Firefighting: overwhelmed by daily problem-solving instead of focusing on proactive improvements',
      'Execution & Day-to-Day Firefighting: struggles managing exceptions in real time (supplier delays, quality issues, capacity constraints)',
      'Partner & Supplier Management: lack of leverage in negotiations with supply chain partners compared to upper management',
      'Partner & Supplier Management: managing compliance with contracted service levels and resolving disputes',
      'Partner & Supplier Management: handling frequent communication breakdowns with suppliers, manufacturers, and distributors',
      'Partner & Supplier Management: frustration with partners not adhering to agreed terms or capacity commitments',
      'Partner & Supplier Management: struggles to maintain balanced supplier relationships while keeping partners engaged',
      'Process Inefficiencies: heavy reliance on manual tools (spreadsheets, email) for supply chain planning and analysis',
      'Process Inefficiencies: limited access to supply chain automation tools that leadership might want but hasn\'t yet invested in',
      'Process Inefficiencies: redundant data entry across supply chain, ERP, and planning systems',
      'Process Inefficiencies: long approval chains slowing down tactical decisions',
      'Data & Visibility Limitations: insufficient visibility into supply chain status after planning',
      'Data & Visibility Limitations: lack of timely reporting for KPIs like supplier performance, lead times, or quality metrics',
      'Data & Visibility Limitations: data scattered across multiple systems, making it hard to analyze performance',
      'Data & Visibility Limitations: struggles to provide upper management with accurate, real-time insights',
      'Cost & Budget Pressures: pressure to cut costs without sacrificing service reliability',
      'Cost & Budget Pressures: limited authority to adjust terms or make exceptions without escalation',
      'Cost & Budget Pressures: constantly balancing budget compliance with operational needs',
      'Cost & Budget Pressures: difficulty justifying small budget overruns tied to unforeseen supply chain disruptions',
      'Stakeholder Coordination: managing expectations from manufacturing, sales, and customer service teams for on-time delivery',
      'Stakeholder Coordination: pressure from leadership for cost savings while front-line teams demand faster turnaround',
      'Stakeholder Coordination: conflict resolution between internal stakeholders and external supply chain partners',
      'Stakeholder Coordination: juggling multiple priorities: service reliability, budget compliance, and customer satisfaction',
      'Talent & Team Management: shortage of staff or over-reliance on a small team to handle large supply chain workloads',
      'Talent & Team Management: difficulty training junior staff on complex supply chain planning and execution tasks',
      'Talent & Team Management: high employee turnover increasing workload on remaining team members',
      'Talent & Team Management: morale challenges due to repetitive manual work and constant firefighting',
      'Technology & Tools: frustration with outdated supply chain and planning systems',
      'Technology & Tools: lack of integration between supply chain platforms, ERP, and visibility tools',
      'Technology & Tools: limited influence on IT/tooling decisions made at higher levels',
      'Technology & Tools: struggles to adopt new digital platforms while keeping up with daily workload',
      'Compliance & Risk: ensuring adherence to corporate supply chain policies during planning',
      'Compliance & Risk: navigating supplier compliance, quality standards, and regulatory requirements',
      'Compliance & Risk: managing the risk of penalties from late deliveries or missed SLAs',
      'Compliance & Risk: difficulty aligning supply chain practices with corporate sustainability initiatives'
    ],
    toneProfile: 'Be actionable and tactical – focus on "what needs to happen next." Provide clarity and guidance – simplify priorities for their teams. Problem-solving tone – address bottlenecks, performance issues, and team management. Collaborative but firm – engage them in decisions while setting clear expectations.',
    keywords: ['supply chain', 'practical', 'hands-on', 'execution', 'team', 'daily', 'coordination', 'implementation', 'management']
  },
  {
    id: 'supply_chain_entry_level',
    label: 'Entry Level - Supply Chain',
    department: 'Supply Chain',
    seniority: 'Entry Level',
    painPoints: [
      'Operational & Process-Related Pain Points: manual, time-consuming supply chain processes with limited automation',
      'Operational & Process-Related Pain Points: difficulty consolidating data across multiple systems (ERP, planning, spreadsheets)',
      'Operational & Process-Related Pain Points: frequent misalignment between supply chain, operations, and finance teams',
      'Operational & Process-Related Pain Points: high administrative workload (supplier management, planning, contract tracking)',
      'Operational & Process-Related Pain Points: difficulty maintaining accurate supply chain and inventory data',
      'Market & Supplier Challenges: volatility in supply chain costs due to raw materials, transportation, and global disruptions',
      'Market & Supplier Challenges: limited visibility into supplier performance and reliability',
      'Market & Supplier Challenges: challenges in building strong supplier relationships at a non-strategic level',
      'Market & Supplier Challenges: difficulty benchmarking performance to ensure competitiveness',
      'Market & Supplier Challenges: limited negotiation power if not a large buyer',
      'Cost & Budget Constraints: pressure to cut costs while ensuring service reliability',
      'Cost & Budget Constraints: difficulty balancing lowest-cost options with service quality and risk',
      'Cost & Budget Constraints: inability to predict or forecast supply chain spend accurately',
      'Cost & Budget Constraints: hidden costs (quality issues, delays, expediting) eroding budgets',
      'Data & Visibility Issues: fragmented data leading to poor real-time visibility into supply chain and inventory',
      'Data & Visibility Issues: lack of standardized KPIs and reporting tools for performance tracking',
      'Data & Visibility Issues: inconsistent data quality across internal and external systems',
      'Data & Visibility Issues: difficulty using analytics to support decision-making',
      'Compliance & Risk: struggles to ensure compliance with contracts, regulations, and quality requirements',
      'Compliance & Risk: limited bandwidth to monitor risk factors (e.g., supplier issues, geopolitical, weather disruptions)',
      'Compliance & Risk: difficulty auditing supply chain invoices and ensuring accuracy',
      'Technology Limitations: reliance on outdated tools (email, Excel) for supply chain planning and execution',
      'Technology Limitations: limited adoption of digital supply chain platforms or automation technologies',
      'Technology Limitations: steep learning curves when adopting new supply chain software',
      'Technology Limitations: integration issues between supply chain tools and ERP systems',
      'Collaboration & Communication: frequent miscommunication between supply chain and operations teams',
      'Collaboration & Communication: lack of transparency with suppliers regarding capacity, lead times, and performance',
      'Collaboration & Communication: challenges in aligning supply chain strategies with broader business goals',
      'Collaboration & Communication: difficulty escalating issues internally when lacking decision-making authority',
      'Career & Role-Specific Pain Points: limited visibility of their work\'s impact on overall supply chain performance',
      'Career & Role-Specific Pain Points: feeling undervalued as supply chain is often seen as a "cost center"',
      'Career & Role-Specific Pain Points: lack of clear career progression paths in supply chain management',
      'Career & Role-Specific Pain Points: high stress due to constant firefighting (supplier issues, urgent orders, last-minute changes)'
    ],
    toneProfile: 'Be instructional and clear – explain expectations and next steps in detail. Encourage learning – break down processes and why they matter. Supportive tone – constructive feedback with focus on skill development. Detail-oriented – emphasize accuracy, process adherence, and reporting quality.',
    keywords: ['supply chain', 'learning', 'development', 'growth', 'support', 'education', 'mentorship', 'career', 'skills']
  },
  {
    id: 'supply_chain_intern',
    label: 'Intern - Supply Chain',
    department: 'Supply Chain',
    seniority: 'Intern',
    painPoints: [
      'Understanding basic supply chain and inventory concepts',
      'Learning company supply chain processes and systems',
      'Managing administrative tasks and data entry',
      'Understanding different supply chain networks and flows',
      'Learning to communicate with suppliers and internal stakeholders',
      'Understanding basic cost and pricing concepts in supply chain',
      'Managing time and meeting deadlines',
      'Learning to use company supply chain software and tools',
      'Understanding basic compliance requirements',
      'Learning to work in a team environment',
      'Understanding the role of technology in supply chain',
      'Learning to analyze basic supply chain performance data',
      'Understanding customer service principles in supply chain',
      'Learning to manage multiple tasks simultaneously',
      'Understanding the impact of external factors on supply chain',
      'Learning to work with different departments',
      'Understanding basic negotiation concepts',
      'Learning to identify process improvements',
      'Understanding the importance of accuracy and attention to detail',
      'Learning to adapt to changing priorities and requirements'
    ],
    toneProfile: 'Be patient and explanatory – over-communicate to ensure understanding. Keep it simple and structured – clear tasks, step-by-step guidance. Encouraging and mentoring – foster curiosity and confidence. Positive and approachable – tone should reduce intimidation and promote engagement.',
    keywords: ['supply chain', 'learning', 'exploration', 'discovery', 'mentorship', 'growth', 'experience', 'development', 'opportunity']
  },
  
  // Sourcing Procurement Department
  {
    id: 'sourcing_procurement_upper_management',
    label: 'Upper Management - Sourcing Procurement',
    department: 'Sourcing Procurement',
    seniority: 'Upper Management',
    painPoints: [
      'Strategic Challenges: balancing cost optimization with supplier relationship management and risk mitigation',
      'Strategic Challenges: limited visibility into end-to-end procurement processes, making it hard to optimize and forecast',
      'Strategic Challenges: difficulty in maintaining procurement flexibility while also committing to long-term supplier contracts',
      'Operational Pain Points: fragmented processes across categories, regions, and business units that hinder standardization',
      'Operational Pain Points: manual, time-consuming sourcing and procurement processes',
      'Operational Pain Points: high administrative overhead due to managing multiple suppliers, contracts, and systems',
      'Operational Pain Points: lack of real-time visibility into procurement status, exceptions, and supplier performance',
      'Cost & Budget Concerns: volatile procurement costs driven by market conditions, supplier capacity, and demand cycles',
      'Cost & Budget Concerns: limited ability to benchmark procurement performance effectively due to inconsistent data',
      'Cost & Budget Concerns: difficulty in proving and tracking procurement savings initiatives to executive stakeholders',
      'Cost & Budget Concerns: over-reliance on reactive sourcing during supply disruptions, leading to unplanned cost spikes',
      'Risk & Compliance: exposure to supplier disruptions (quality issues, capacity constraints, geopolitical tensions, weather)',
      'Risk & Compliance: risk of supplier insolvency or underperformance affecting service levels',
      'Risk & Compliance: lack of standardized processes for supplier vetting and onboarding',
      'Technology & Data Gaps: disparate systems across sourcing, procurement, and finance teams that don\'t integrate',
      'Technology & Data Gaps: poor quality or incomplete procurement data limiting analytics and decision-making',
      'Technology & Data Gaps: difficulty adopting modern digital procurement tools at scale',
      'Technology & Data Gaps: resistance to change from teams accustomed to legacy/manual processes',
      'Supplier & Partner Management: maintaining strong relationships with suppliers while also pushing for better terms',
      'Supplier & Partner Management: balancing strategic supplier partnerships with the need for diversification to reduce dependency',
      'Supplier & Partner Management: limited visibility into supplier performance metrics and KPIs across categories',
      'Supplier & Partner Management: difficulty in negotiating fair terms during volatile market conditions',
      'Talent & Organizational Pressures: shortage of procurement professionals with advanced analytics and digital procurement skills',
      'Talent & Organizational Pressures: high expectations from executive leadership to deliver cost savings and efficiency improvements quickly',
      'Talent & Organizational Pressures: challenges in retaining top talent in a competitive procurement labor market'
    ],
    toneProfile: 'Be strategic with operational depth – balance long-term goals with actionable next steps. Use comparative insights – benchmark performance, highlight best practices. Show resource allocation impact – budgets, technology adoption, supplier choices. Confident and professional – present clear recommendations backed by data.',
    keywords: ['sourcing', 'procurement', 'management', 'efficiency', 'team', 'process', 'departmental', 'leadership', 'productivity']
  },
  {
    id: 'sourcing_procurement_middle_management',
    label: 'Middle Management - Sourcing Procurement',
    department: 'Sourcing Procurement',
    seniority: 'Middle Management',
    painPoints: [
      'Execution & Day-to-Day Firefighting: constantly dealing with last-minute procurement changes, supplier issues, and disruptions',
      'Execution & Day-to-Day Firefighting: difficulty reallocating sourcing when suppliers fail to deliver',
      'Execution & Day-to-Day Firefighting: overwhelmed by daily problem-solving instead of focusing on proactive improvements',
      'Execution & Day-to-Day Firefighting: struggles managing exceptions in real time (supplier delays, quality issues, capacity constraints)',
      'Supplier & Partner Management: lack of leverage in negotiations with suppliers compared to upper management',
      'Supplier & Partner Management: managing compliance with contracted terms and resolving disputes',
      'Supplier & Partner Management: handling frequent communication breakdowns with suppliers and internal stakeholders',
      'Supplier & Partner Management: frustration with suppliers not adhering to agreed terms or delivery commitments',
      'Supplier & Partner Management: struggles to maintain balanced supplier relationships while keeping suppliers engaged',
      'Process Inefficiencies: heavy reliance on manual tools (spreadsheets, email) for sourcing and procurement analysis',
      'Process Inefficiencies: limited access to procurement automation tools that leadership might want but hasn\'t yet invested in',
      'Process Inefficiencies: redundant data entry across sourcing, procurement, and ERP systems',
      'Process Inefficiencies: long approval chains slowing down tactical decisions',
      'Data & Visibility Limitations: insufficient visibility into procurement status after sourcing',
      'Data & Visibility Limitations: lack of timely reporting for KPIs like supplier performance, cost savings, or quality metrics',
      'Data & Visibility Limitations: data scattered across multiple systems, making it hard to analyze performance',
      'Data & Visibility Limitations: struggles to provide upper management with accurate, real-time insights',
      'Cost & Budget Pressures: pressure to cut costs without sacrificing service reliability',
      'Cost & Budget Pressures: limited authority to adjust terms or make exceptions without escalation',
      'Cost & Budget Pressures: constantly balancing budget compliance with operational needs',
      'Cost & Budget Pressures: difficulty justifying small budget overruns tied to unforeseen procurement disruptions',
      'Stakeholder Coordination: managing expectations from operations, finance, and quality teams for on-time delivery',
      'Stakeholder Coordination: pressure from leadership for cost savings while front-line teams demand faster turnaround',
      'Stakeholder Coordination: conflict resolution between internal stakeholders and external suppliers',
      'Stakeholder Coordination: juggling multiple priorities: service reliability, budget compliance, and quality standards',
      'Talent & Team Management: shortage of staff or over-reliance on a small team to handle large procurement workloads',
      'Talent & Team Management: difficulty training junior staff on complex sourcing and procurement tasks',
      'Talent & Team Management: high employee turnover increasing workload on remaining team members',
      'Talent & Team Management: morale challenges due to repetitive manual work and constant firefighting',
      'Technology & Tools: frustration with outdated sourcing and procurement systems',
      'Technology & Tools: lack of integration between procurement platforms, ERP, and supplier systems',
      'Technology & Tools: limited influence on IT/tooling decisions made at higher levels',
      'Technology & Tools: struggles to adopt new digital platforms while keeping up with daily workload',
      'Compliance & Risk: ensuring adherence to corporate procurement policies during sourcing',
      'Compliance & Risk: navigating supplier compliance, quality standards, and regulatory requirements',
      'Compliance & Risk: managing the risk of penalties from late deliveries or missed SLAs',
      'Compliance & Risk: difficulty aligning procurement practices with corporate sustainability initiatives'
    ],
    toneProfile: 'Be actionable and tactical – focus on "what needs to happen next." Provide clarity and guidance – simplify priorities for their teams. Problem-solving tone – address bottlenecks, performance issues, and team management. Collaborative but firm – engage them in decisions while setting clear expectations.',
    keywords: ['sourcing', 'procurement', 'practical', 'hands-on', 'execution', 'team', 'daily', 'coordination', 'implementation', 'management']
  },
  {
    id: 'sourcing_procurement_entry_level',
    label: 'Entry Level - Sourcing Procurement',
    department: 'Sourcing Procurement',
    seniority: 'Entry Level',
    painPoints: [
      'Operational & Process-Related Pain Points: manual, time-consuming procurement processes with limited automation',
      'Operational & Process-Related Pain Points: difficulty consolidating data across multiple systems (ERP, sourcing, spreadsheets)',
      'Operational & Process-Related Pain Points: frequent misalignment between procurement, operations, and finance teams',
      'Operational & Process-Related Pain Points: high administrative workload (supplier management, sourcing, contract tracking)',
      'Operational & Process-Related Pain Points: difficulty maintaining accurate procurement and supplier data',
      'Market & Supplier Challenges: volatility in procurement costs due to market conditions, supplier capacity, and global disruptions',
      'Market & Supplier Challenges: limited visibility into supplier performance and reliability',
      'Market & Supplier Challenges: challenges in building strong supplier relationships at a non-strategic level',
      'Market & Supplier Challenges: difficulty benchmarking performance to ensure competitiveness',
      'Market & Supplier Challenges: limited negotiation power if not a large buyer',
      'Cost & Budget Constraints: pressure to cut costs while ensuring service reliability',
      'Cost & Budget Constraints: difficulty balancing lowest-cost options with service quality and risk',
      'Cost & Budget Constraints: inability to predict or forecast procurement spend accurately',
      'Cost & Budget Constraints: hidden costs (quality issues, delays, expediting) eroding budgets',
      'Data & Visibility Issues: fragmented data leading to poor real-time visibility into procurement and supplier performance',
      'Data & Visibility Issues: lack of standardized KPIs and reporting tools for performance tracking',
      'Data & Visibility Issues: inconsistent data quality across internal and external systems',
      'Data & Visibility Issues: difficulty using analytics to support decision-making',
      'Compliance & Risk: struggles to ensure compliance with contracts, regulations, and quality requirements',
      'Compliance & Risk: limited bandwidth to monitor risk factors (e.g., supplier issues, geopolitical, weather disruptions)',
      'Compliance & Risk: difficulty auditing procurement invoices and ensuring accuracy',
      'Technology Limitations: reliance on outdated tools (email, Excel) for sourcing and procurement',
      'Technology Limitations: limited adoption of digital procurement platforms or automation technologies',
      'Technology Limitations: steep learning curves when adopting new procurement software',
      'Technology Limitations: integration issues between procurement tools and ERP systems',
      'Collaboration & Communication: frequent miscommunication between procurement and operations teams',
      'Collaboration & Communication: lack of transparency with suppliers regarding capacity, lead times, and performance',
      'Collaboration & Communication: challenges in aligning procurement strategies with broader business goals',
      'Collaboration & Communication: difficulty escalating issues internally when lacking decision-making authority',
      'Career & Role-Specific Pain Points: limited visibility of their work\'s impact on overall procurement performance',
      'Career & Role-Specific Pain Points: feeling undervalued as procurement is often seen as a "cost center"',
      'Career & Role-Specific Pain Points: lack of clear career progression paths in procurement management',
      'Career & Role-Specific Pain Points: high stress due to constant firefighting (supplier issues, urgent orders, last-minute changes)'
    ],
    toneProfile: 'Be instructional and clear – explain expectations and next steps in detail. Encourage learning – break down processes and why they matter. Supportive tone – constructive feedback with focus on skill development. Detail-oriented – emphasize accuracy, process adherence, and reporting quality.',
    keywords: ['sourcing', 'procurement', 'learning', 'development', 'growth', 'support', 'education', 'mentorship', 'career', 'skills']
  },
  {
    id: 'sourcing_procurement_intern',
    label: 'Intern - Sourcing Procurement',
    department: 'Sourcing Procurement',
    seniority: 'Intern',
    painPoints: [
      'Understanding basic sourcing and procurement concepts',
      'Learning company procurement processes and systems',
      'Managing administrative tasks and data entry',
      'Understanding different sourcing strategies and supplier networks',
      'Learning to communicate with suppliers and internal stakeholders',
      'Understanding basic cost and pricing concepts in procurement',
      'Managing time and meeting deadlines',
      'Learning to use company procurement software and tools',
      'Understanding basic compliance requirements',
      'Learning to work in a team environment',
      'Understanding the role of technology in procurement',
      'Learning to analyze basic procurement performance data',
      'Understanding customer service principles in procurement',
      'Learning to manage multiple tasks simultaneously',
      'Understanding the impact of external factors on procurement',
      'Learning to work with different departments',
      'Understanding basic negotiation concepts',
      'Learning to identify process improvements',
      'Understanding the importance of accuracy and attention to detail',
      'Learning to adapt to changing priorities and requirements'
    ],
    toneProfile: 'Be patient and explanatory – over-communicate to ensure understanding. Keep it simple and structured – clear tasks, step-by-step guidance. Encouraging and mentoring – foster curiosity and confidence. Positive and approachable – tone should reduce intimidation and promote engagement.',
    keywords: ['sourcing', 'procurement', 'learning', 'exploration', 'discovery', 'mentorship', 'growth', 'experience', 'development', 'opportunity']
  }
]

// Helper function to get persona by ID
export function getPersonaById(id: string): PersonaDefinition | undefined {
  return PERSONA_DEFINITIONS.find(persona => persona.id === id)
}

// Helper function to get personas by department
export function getPersonasByDepartment(department: 'Operations' | 'Finance' | 'Logistics' | 'Supply Chain' | 'Sourcing Procurement'): PersonaDefinition[] {
  return PERSONA_DEFINITIONS.filter(persona => persona.department === department)
}

// Helper function to get personas by seniority
export function getPersonasBySeniority(seniority: 'C-Suite' | 'Upper Management' | 'Middle Management' | 'Entry Level' | 'Intern'): PersonaDefinition[] {
  return PERSONA_DEFINITIONS.filter(persona => persona.seniority === seniority)
}
