// Detailed persona definitions with pain points and tone profiles

export interface PersonaDefinition {
  id: string
  label: string
  department: 'Operations' | 'Finance'
  seniority: 'C-Suite' | 'Upper Management' | 'Middle Management' | 'Entry Level' | 'Intern'
  painPoints: string[]
  toneProfile: string
  keywords: string[]
}

export const PERSONA_DEFINITIONS: PersonaDefinition[] = [
  // Operations Department
  {
    id: 'ceo',
    label: 'CEO',
    department: 'Operations',
    seniority: 'C-Suite',
    painPoints: [
      'Strategic Challenges: balancing shareholder demands for profitability with resilient, sustainable freight procurement',
      'Strategic Challenges: limited visibility into how freight costs impact overall corporate strategy',
      'Strategic Challenges: difficulty aligning freight procurement with growth goals',
      'Operational Pain Points: fragmented procurement practices across business units reducing efficiency',
      'Operational Pain Points: over-reliance on outdated procurement models that limit agility',
      'Operational Pain Points: inefficient communication between freight procurement and other strategic functions (finance, sales, operations)',
      'Cost & Budget Concerns: freight spend volatility creating uncertainty for earnings forecasts',
      'Cost & Budget Concerns: difficulty ensuring procurement cost savings flow through to P&L results',
      'Cost & Budget Concerns: unpredictable global freight markets affecting long-term financial planning',
      'Risk & Compliance: exposure to high-profile disruptions (geopolitical, climate, regulatory)',
      'Risk & Compliance: insufficient processes to safeguard against fraud or weak carrier vetting',
      'Technology & Data Gaps: lack of enterprise-wide freight visibility tools tied to executive dashboards',
      'Technology & Data Gaps: disparate systems that limit a single view of procurement impact',
      'Technology & Data Gaps: slow adoption of modern freight procurement technologies across regions',
      'Carrier & Supplier Management: difficulty balancing reliance on strategic partners with need for diversification',
      'Carrier & Supplier Management: limited visibility into supplier/carrier health and performance at board level',
      'Carrier & Supplier Management: tensions between cost-driven decisions and long-term relationship building',
      'Talent & Organizational Pressures: pressure on leadership to attract talent capable of modernizing freight procurement',
      'Talent & Organizational Pressures: need to foster cross-functional collaboration between finance, procurement, and operations'
    ],
    toneProfile: 'Strategic, executive-level language focusing on ROI, scalability, and enterprise-wide impact. Use terms like "strategic initiatives," "enterprise-wide," "C-level visibility," and "board-level metrics." Emphasize high-level business outcomes and competitive advantage.',
    keywords: ['strategic', 'enterprise', 'roi', 'scalability', 'executive', 'board', 'competitive advantage', 'enterprise-wide']
  },
  {
    id: 'coo',
    label: 'COO',
    department: 'Operations',
    seniority: 'C-Suite',
    painPoints: [
      'Strategic Challenges: translating the CEO\'s vision into executable operational strategies',
      'Strategic Challenges: balancing growth, efficiency, and agility in a fast-changing environment',
      'Strategic Challenges: scaling operations to support expansion while keeping costs under control',
      'Strategic Challenges: driving digital transformation without disrupting current operations',
      'Operational Efficiency: eliminating silos between business units to improve collaboration',
      'Operational Efficiency: streamlining processes and reducing inefficiencies in workflows',
      'Operational Efficiency: maintaining consistent performance across global operations',
      'Operational Efficiency: managing supply chain complexity, lead times, and logistics disruptions',
      'Operational Efficiency: balancing standardization with the need for local market flexibility',
      'Risk & Compliance: ensuring compliance with operational, legal, and industry regulations',
      'Risk & Compliance: managing operational risks, including supply chain disruptions, safety incidents, and business continuity',
      'Risk & Compliance: implementing effective crisis management and disaster recovery plans',
      'Risk & Compliance: maintaining quality assurance across diverse operations',
      'Data & Technology: gaining visibility into operational performance in real-time',
      'Data & Technology: integrating disparate systems (ERP, supply chain, HR, finance) into a cohesive platform',
      'Data & Technology: leveraging data analytics to drive decision-making and process improvements',
      'Data & Technology: adopting automation, AI, and robotics while managing workforce impact',
      'Data & Technology: balancing investment in new technology against ROI and adoption challenges',
      'Customer & Market Demands: meeting evolving customer expectations for speed, quality, and personalization',
      'Customer & Market Demands: ensuring customer experience aligns with operational capabilities',
      'Customer & Market Demands: responding quickly to competitor moves and market shifts',
      'Customer & Market Demands: balancing operational capacity with fluctuating demand',
      'Cost & Resource Management: managing rising operational costs (labor, logistics, raw materials, energy)',
      'Cost & Resource Management: optimizing resource allocation to achieve efficiency and growth',
      'Cost & Resource Management: reducing waste in production, logistics, and service delivery',
      'Cost & Resource Management: demonstrating operational value beyond cost cutting (e.g., resilience, agility)',
      'Leadership & Talent: attracting, developing, and retaining talent across multiple functions',
      'Leadership & Talent: leading cross-functional teams with diverse skills and priorities',
      'Leadership & Talent: building a culture of continuous improvement and accountability',
      'Leadership & Talent: overcoming resistance to operational change and transformation initiatives',
      'Leadership & Talent: preparing future leaders and succession planning for critical roles',
      'External Pressures: navigating geopolitical uncertainty, trade wars, and global instability',
      'External Pressures: managing environmental and sustainability expectations (green operations, carbon footprint reduction)',
      'External Pressures: coping with economic volatility, inflation, and fluctuating demand cycles',
      'External Pressures: maintaining competitive advantage in industries under rapid disruption'
    ],
    toneProfile: 'Operational, execution-focused language emphasizing efficiency, standardization, and operational excellence. Use terms like "operational efficiency," "process standardization," "service reliability," and "operational metrics." Focus on execution and operational outcomes.',
    keywords: ['operational', 'efficiency', 'standardization', 'execution', 'service', 'reliability', 'process', 'operations']
  },
  {
    id: 'cfo',
    label: 'CFO',
    department: 'Finance',
    seniority: 'C-Suite',
    painPoints: [
      'Strategic Challenges: balancing short-term financial performance with long-term growth strategy',
      'Strategic Challenges: driving digital transformation while maintaining financial discipline',
      'Strategic Challenges: navigating M&A (mergers & acquisitions), investments, and divestitures',
      'Financial Management: maintaining accurate forecasting in volatile markets',
      'Financial Management: managing cash flow and liquidity under uncertainty',
      'Financial Management: reducing costs without stifling innovation or growth',
      'Financial Management: optimizing capital allocation across competing priorities',
      'Risk & Compliance: keeping up with constantly changing regulations and tax laws',
      'Risk & Compliance: managing audit requirements and avoiding compliance penalties',
      'Risk & Compliance: monitoring financial risks, fraud, and cybersecurity threats',
      'Risk & Compliance: ensuring robust internal controls and governance structures',
      'Data & Technology: integrating disparate financial systems and data sources',
      'Data & Technology: gaining real-time visibility into company performance',
      'Data & Technology: turning financial data into actionable insights for decision-making',
      'Data & Technology: adopting AI/automation while managing associated risks',
      'Leadership & Talent: building and retaining a high-performing finance team',
      'Leadership & Talent: upscaling finance staff for analytics and digital tools',
      'Leadership & Talent: aligning finance with cross-functional business partners',
      'Leadership & Talent: managing organizational resistance to financial discipline',
      'External Pressures: meeting shareholder and board expectations for growth and profitability',
      'External Pressures: communicating effectively with investors, analysts, and stakeholders',
      'External Pressures: handling economic pressures such as inflation, interest rate changes, and currency fluctuations',
      'External Pressures: competing with industry peers in financial efficiency and reporting transparency'
    ],
    toneProfile: 'Financial, analytical language emphasizing cost control, risk management, and financial performance. Use terms like "cost optimization," "financial performance," "risk mitigation," and "ROI validation." Focus on financial outcomes and stakeholder value.',
    keywords: ['financial', 'cost', 'optimization', 'performance', 'risk', 'roi', 'analytics', 'stakeholder']
  },
  {
    id: 'cpo',
    label: 'CPO (Chief Procurement Officer)',
    department: 'Operations',
    seniority: 'C-Suite',
    painPoints: [
      'Strategic Challenges: balancing long-term supplier partnerships with short-term cost savings',
      'Strategic Challenges: lack of alignment between procurement and other supply chain stakeholders',
      'Operational Pain Points: manual, time-consuming tendering processes',
      'Operational Pain Points: fragmented workflows across global procurement teams',
      'Operational Pain Points: high administrative burden in managing multiple carriers and brokers',
      'Cost & Budget Concerns: fluctuating freight costs complicating budgeting and savings targets',
      'Cost & Budget Concerns: limited ability to benchmark carrier pricing across markets',
      'Cost & Budget Concerns: challenges proving procurement-driven cost savings',
      'Risk & Compliance: inadequate processes for carrier onboarding and vetting',
      'Risk & Compliance: risk of relying on a narrow set of carriers during disruptions',
      'Technology & Data Gaps: lack of integration between procurement tools and logistics platforms',
      'Technology & Data Gaps: poor data availability for rate benchmarking and performance analysis',
      'Technology & Data Gaps: slow adoption of digital freight procurement solutions at scale',
      'Carrier & Supplier Management: difficulty balancing strategic carrier relationships with diversification needs',
      'Carrier & Supplier Management: limited visibility into carrier performance across all modes',
      'Carrier & Supplier Management: strain in negotiations during volatile capacity markets',
      'Talent & Organizational Pressures: shortage of procurement professionals with analytics and digital skills',
      'Talent & Organizational Pressures: pressure to deliver measurable savings and efficiency gains quickly',
      'Talent & Organizational Pressures: high turnover in procurement roles due to competitive market'
    ],
    toneProfile: 'Procurement-focused language emphasizing supplier relationships, cost optimization, and strategic sourcing. Use terms like "strategic sourcing," "supplier partnerships," "cost optimization," and "procurement excellence." Focus on procurement strategy and supplier management.',
    keywords: ['procurement', 'sourcing', 'supplier', 'partnerships', 'cost', 'optimization', 'strategic', 'excellence']
  },
  {
    id: 'csco',
    label: 'CSCO (Chief Supply Chain Officer)',
    department: 'Operations',
    seniority: 'C-Suite',
    painPoints: [
      'Strategic Challenges: balancing supply chain resilience with procurement cost efficiency',
      'Strategic Challenges: ensuring freight procurement supports customer service expectations',
      'Strategic Challenges: aligning procurement with sustainability and decarbonization targets',
      'Operational Pain Points: fragmented freight procurement processes across regions and modes',
      'Operational Pain Points: lack of real-time shipment visibility impacting planning accuracy',
      'Operational Pain Points: disruptions requiring reactive, manual interventions',
      'Cost & Budget Concerns: unpredictable freight costs complicating supply chain cost optimization',
      'Cost & Budget Concerns: over-dependence on spot market driving unplanned budget spikes',
      'Cost & Budget Concerns: difficulty tying freight costs directly to product margins',
      'Risk & Compliance: high exposure to global disruptions (weather, strikes, geopolitics)',
      'Risk & Compliance: lack of standardized carrier vetting processes',
      'Risk & Compliance: vulnerability to reputational risk from non-compliant suppliers',
      'Technology & Data Gaps: disparate systems preventing end-to-end supply chain visibility',
      'Technology & Data Gaps: poor freight data limiting predictive planning capabilities',
      'Carrier & Supplier Management: tension between strategic partnerships and diversification for resilience',
      'Carrier & Supplier Management: limited visibility into carrier KPIs at the executive level',
      'Carrier & Supplier Management: difficulty maintaining service quality during cost negotiations',
      'Talent & Organizational Pressures: shortage of supply chain professionals with digital freight expertise',
      'Talent & Organizational Pressures: executive pressure to deliver resilient, cost-efficient supply chains',
      'Talent & Organizational Pressures: retention challenges due to high competition for top talent'
    ],
    toneProfile: 'Supply chain-focused language emphasizing resilience, customer service, and end-to-end optimization. Use terms like "supply chain resilience," "customer service," "end-to-end visibility," and "sustainability." Focus on supply chain strategy and customer impact.',
    keywords: ['supply chain', 'resilience', 'customer', 'service', 'visibility', 'sustainability', 'optimization', 'strategy']
  },
  {
    id: 'owner_founder',
    label: 'Owner / Founder',
    department: 'Operations',
    seniority: 'C-Suite',
    painPoints: [
      'Strategic & Vision Challenges: balancing long-term vision with short-term execution pressures',
      'Strategic & Vision Challenges: difficulty in prioritizing opportunities vs. distractions',
      'Strategic & Vision Challenges: adapting business strategy to rapidly changing market conditions',
      'Strategic & Vision Challenges: fear of stagnation or being disrupted by competitors',
      'Financial & Resource Strain: securing consistent cash flow and funding',
      'Financial & Resource Strain: managing investor expectations while protecting company culture',
      'Financial & Resource Strain: budget allocation trade-offs between growth and sustainability',
      'People & Leadership Struggles: recruiting and retaining top talent in a competitive market',
      'People & Leadership Struggles: building and maintaining strong leadership teams',
      'People & Leadership Struggles: managing conflict among co-founders or senior leadership',
      'People & Leadership Struggles: balancing empathy with performance accountability',
      'Operational Burdens: wearing too many hats, especially in early stages',
      'Operational Burdens: lack of time to focus deeply due to constant context switching',
      'Operational Burdens: building scalable systems and processes without over-engineering',
      'Market & Growth Pressures: finding product-market fit (for early-stage founders)',
      'Market & Growth Pressures: sustaining growth without sacrificing quality or culture',
      'Market & Growth Pressures: differentiating in crowded, competitive markets',
      'Market & Growth Pressures: scaling sales and marketing efficiently',
      'Personal Stress & Wellbeing: high levels of stress, anxiety, and burnout',
      'Personal Stress & Wellbeing: loneliness in decision-making ("founder\'s isolation")',
      'Personal Stress & Wellbeing: difficulty maintaining work-life balance',
      'Personal Stress & Wellbeing: pressure of being the ultimate decision-maker',
      'Reputation & Legacy Concerns: protecting brand reputation in a hyper-visible digital era',
      'Reputation & Legacy Concerns: ensuring long-term impact beyond short-term wins',
      'Reputation & Legacy Concerns: concerns about succession planning and company legacy'
    ],
    toneProfile: 'Visionary, personal language emphasizing growth, innovation, and leadership. Use terms like "vision," "growth," "innovation," "leadership," and "impact." Focus on personal leadership and company vision.',
    keywords: ['vision', 'growth', 'innovation', 'leadership', 'impact', 'founder', 'entrepreneur', 'strategy']
  },
  {
    id: 'operations_upper_management',
    label: 'Upper Management - Operations',
    department: 'Operations',
    seniority: 'Upper Management',
    painPoints: [
      'Strategic Challenges: balancing cost optimization with service reliability and customer expectations',
      'Strategic Challenges: limited visibility into end-to-end freight costs, making it hard to forecast and budget accurately',
      'Strategic Challenges: difficulty in maintaining flexibility while also committing to long-term carrier contracts',
      'Operational Pain Points: fragmented processes across regions, modes, and business units that hinder standardization',
      'Operational Pain Points: manual, time-consuming tendering and carrier selection processes',
      'Operational Pain Points: high administrative overhead due to managing multiple carriers, freight forwarders, and brokers',
      'Operational Pain Points: lack of real-time visibility into shipment status, exceptions, and disruptions',
      'Cost & Budget Concerns: volatile freight rates driven by fuel prices, geopolitical issues, and market cycles',
      'Cost & Budget Concerns: limited ability to benchmark carrier rates effectively due to inconsistent data',
      'Cost & Budget Concerns: difficulty in proving and tracking cost savings initiatives to executive stakeholders',
      'Cost & Budget Concerns: over-reliance on spot markets during capacity crunches, leading to unplanned cost spikes',
      'Risk & Compliance: exposure to supply chain disruptions (port congestion, strikes, geopolitical tensions, weather)',
      'Risk & Compliance: risk of carrier insolvency or underperformance affecting service levels',
      'Risk & Compliance: lack of standardized processes for supplier/carrier vetting and onboarding',
      'Technology & Data Gaps: disparate systems across transportation, procurement, and finance teams that don\'t integrate',
      'Technology & Data Gaps: poor quality or incomplete freight data limiting analytics and decision-making',
      'Technology & Data Gaps: difficulty adopting modern digital freight procurement tools at scale',
      'Technology & Data Gaps: resistance to change from teams accustomed to legacy/manual processes',
      'Carrier & Supplier Management: maintaining strong relationships with carriers while also pushing for lower rates',
      'Carrier & Supplier Management: balancing strategic carrier partnerships with the need for diversification to reduce dependency',
      'Carrier & Supplier Management: limited visibility into carrier performance metrics and KPIs across modes',
      'Carrier & Supplier Management: difficulty in negotiating fair contract terms during volatile capacity markets',
      'Talent & Organizational Pressures: shortage of supply chain professionals with advanced analytics and digital procurement skills',
      'Talent & Organizational Pressures: high expectations from executive leadership to deliver cost savings and efficiency improvements quickly',
      'Talent & Organizational Pressures: challenges in retaining top talent in a competitive supply chain labor market'
    ],
    toneProfile: 'Management-focused language emphasizing operational efficiency, team leadership, and departmental impact. Use terms like "operational excellence," "team productivity," "process optimization," and "departmental metrics." Focus on practical solutions and team management challenges.',
    keywords: ['operational', 'management', 'efficiency', 'team', 'process', 'departmental', 'leadership', 'productivity']
  },
  {
    id: 'operations_middle_management',
    label: 'Middle Management - Operations',
    department: 'Operations',
    seniority: 'Middle Management',
    painPoints: [
      'Execution & Day-to-Day Firefighting: constantly dealing with last-minute shipment changes, delays, and disruptions',
      'Execution & Day-to-Day Firefighting: difficulty reallocating loads when carriers reject tenders or fail to show',
      'Execution & Day-to-Day Firefighting: overwhelmed by daily problem-solving instead of focusing on proactive improvements',
      'Execution & Day-to-Day Firefighting: struggles managing exceptions in real time (detention, demurrage, customs issues)',
      'Carrier & Supplier Management: lack of leverage in negotiations with carriers compared to upper management',
      'Carrier & Supplier Management: managing compliance with contracted service levels and resolving disputes',
      'Carrier & Supplier Management: handling frequent communication breakdowns with carriers and brokers',
      'Carrier & Supplier Management: frustration with carriers not adhering to agreed pricing or capacity commitments',
      'Carrier & Supplier Management: struggles to maintain balanced routing guides while keeping carriers engaged',
      'Process Inefficiencies: heavy reliance on manual tools (spreadsheets, email) for bid collection and analysis',
      'Process Inefficiencies: limited access to procurement automation tools that leadership might want but hasn\'t yet invested in',
      'Process Inefficiencies: redundant data entry across procurement, TMS, and ERP systems',
      'Process Inefficiencies: long approval chains slowing down tactical decisions',
      'Data & Visibility Limitations: insufficient visibility into shipment status after awarding freight',
      'Data & Visibility Limitations: lack of timely reporting for KPIs like carrier performance, lane costs, or service failures',
      'Data & Visibility Limitations: data scattered across multiple systems, making it hard to analyze performance',
      'Data & Visibility Limitations: struggles to provide upper management with accurate, real-time insights',
      'Cost & Budget Pressures: pressure to cut costs without sacrificing service reliability',
      'Cost & Budget Pressures: limited authority to adjust pricing or make exceptions without escalation',
      'Cost & Budget Pressures: constantly balancing budget compliance with operational needs',
      'Cost & Budget Pressures: difficulty justifying small budget overruns tied to unforeseen surcharges or accessorials',
      'Stakeholder Coordination: managing expectations from warehouse, operations, and sales teams for on-time shipments',
      'Stakeholder Coordination: pressure from leadership for cost savings while front-line teams demand faster turnaround',
      'Stakeholder Coordination: conflict resolution between internal stakeholders and external carriers',
      'Stakeholder Coordination: juggling multiple priorities: service reliability, budget compliance, and customer satisfaction',
      'Talent & Team Management: shortage of staff or over-reliance on a small team to handle large procurement workloads',
      'Talent & Team Management: difficulty training junior staff on complex sourcing and negotiation tasks',
      'Talent & Team Management: high employee turnover increasing workload on remaining team members',
      'Talent & Team Management: morale challenges due to repetitive manual work and constant firefighting',
      'Technology & Tools: frustration with outdated procurement and logistics systems',
      'Technology & Tools: lack of integration between procurement platforms, TMS, and visibility tools',
      'Technology & Tools: limited influence on IT/tooling decisions made at higher levels',
      'Technology & Tools: struggles to adopt new digital platforms while keeping up with daily workload',
      'Compliance & Risk: ensuring adherence to corporate procurement policies during sourcing',
      'Compliance & Risk: navigating carrier insurance, safety records, and regulatory compliance',
      'Compliance & Risk: managing the risk of penalties from late deliveries or missed SLAs',
      'Compliance & Risk: difficulty aligning sourcing practices with corporate sustainability initiatives'
    ],
    toneProfile: 'Practical, hands-on language focusing on execution, team management, and daily operations. Use terms like "day-to-day," "hands-on," "practical solutions," "team coordination," and "operational execution." Emphasize practical implementation and team management.',
    keywords: ['practical', 'hands-on', 'execution', 'team', 'daily', 'coordination', 'implementation', 'management']
  },
  {
    id: 'operations_entry_level',
    label: 'Entry Level - Operations',
    department: 'Operations',
    seniority: 'Entry Level',
    painPoints: [
      'Operational & Process-Related Pain Points: manual, time-consuming procurement processes with limited automation',
      'Operational & Process-Related Pain Points: difficulty consolidating data across multiple systems (TMS, ERP, spreadsheets)',
      'Operational & Process-Related Pain Points: frequent misalignment between procurement, operations, and finance teams',
      'Operational & Process-Related Pain Points: high administrative workload (rate requests, tender management, contract tracking)',
      'Operational & Process-Related Pain Points: difficulty maintaining accurate shipment and freight cost data',
      'Market & Supplier Challenges: volatility in freight rates due to fuel costs, capacity fluctuations, and global disruptions',
      'Market & Supplier Challenges: limited visibility into carrier performance and reliability',
      'Market & Supplier Challenges: challenges in building strong supplier/carrier relationships at a non-strategic level',
      'Market & Supplier Challenges: difficulty benchmarking rates to ensure competitiveness',
      'Market & Supplier Challenges: limited negotiation power if not a large shipper',
      'Cost & Budget Constraints: pressure to cut costs while ensuring service reliability',
      'Cost & Budget Constraints: difficulty balancing lowest-cost bids with service quality and risk',
      'Cost & Budget Constraints: inability to predict or forecast freight spend accurately',
      'Cost & Budget Constraints: hidden costs (detention, demurrage, surcharges) eroding budgets',
      'Data & Visibility Issues: fragmented data leading to poor real-time visibility into shipments and spend',
      'Data & Visibility Issues: lack of standardized KPIs and reporting tools for performance tracking',
      'Data & Visibility Issues: inconsistent data quality across internal and external systems',
      'Data & Visibility Issues: difficulty using analytics to support decision-making',
      'Compliance & Risk: struggles to ensure compliance with contracts, regulations, and trade requirements',
      'Compliance & Risk: limited bandwidth to monitor risk factors (e.g., geopolitical, port strikes, weather disruptions)',
      'Compliance & Risk: difficulty auditing freight invoices and ensuring accuracy',
      'Technology Limitations: reliance on outdated tools (email, Excel) for procurement and bidding',
      'Technology Limitations: limited adoption of digital freight platforms or automation technologies',
      'Technology Limitations: steep learning curves when adopting new procurement software',
      'Technology Limitations: integration issues between procurement tools and logistics systems',
      'Collaboration & Communication: frequent miscommunication between procurement and operations teams',
      'Collaboration & Communication: lack of transparency with carriers regarding capacity, rates, and performance',
      'Collaboration & Communication: challenges in aligning procurement strategies with broader supply chain goals',
      'Collaboration & Communication: difficulty escalating issues internally when lacking decision-making authority',
      'Career & Role-Specific Pain Points: limited visibility of their work\'s impact on overall supply chain performance',
      'Career & Role-Specific Pain Points: feeling undervalued as procurement is often seen as a "cost center"',
      'Career & Role-Specific Pain Points: lack of clear career progression paths in freight procurement',
      'Career & Role-Specific Pain Points: high stress due to constant firefighting (spot buys, urgent shipments, last-minute changes)'
    ],
    toneProfile: 'Supportive, educational language focusing on learning, growth, and skill development. Use terms like "learning opportunity," "skill development," "career growth," "mentorship," and "professional development." Emphasize support and learning.',
    keywords: ['learning', 'development', 'growth', 'support', 'education', 'mentorship', 'career', 'skills']
  },
  {
    id: 'operations_intern',
    label: 'Intern - Operations',
    department: 'Operations',
    seniority: 'Intern',
    painPoints: [
      'Understanding basic freight and logistics concepts',
      'Learning company processes and systems',
      'Managing administrative tasks and data entry',
      'Understanding different transportation modes',
      'Learning to communicate with carriers and customers',
      'Understanding basic cost and pricing concepts',
      'Managing time and meeting deadlines',
      'Learning to use company software and tools',
      'Understanding basic compliance requirements',
      'Learning to work in a team environment',
      'Understanding the role of technology in logistics',
      'Learning to analyze basic performance data',
      'Understanding customer service principles',
      'Learning to manage multiple tasks simultaneously',
      'Understanding the impact of external factors',
      'Learning to work with different departments',
      'Understanding basic negotiation concepts',
      'Learning to identify process improvements',
      'Understanding the importance of accuracy and attention to detail',
      'Learning to adapt to changing priorities and requirements'
    ],
    toneProfile: 'Encouraging, educational language focusing on learning, exploration, and professional development. Use terms like "learning experience," "exploration," "discovery," "mentorship," and "professional growth." Emphasize learning and development opportunities.',
    keywords: ['learning', 'exploration', 'discovery', 'mentorship', 'growth', 'experience', 'development', 'opportunity']
  },
  // Finance Department
  {
    id: 'finance_c_suite',
    label: 'C-Suite - Finance',
    department: 'Finance',
    seniority: 'C-Suite',
    painPoints: [
      'Strategic financial planning and budgeting challenges',
      'Limited visibility into transportation cost drivers',
      'Difficulty forecasting freight costs accurately',
      'Managing financial risk in volatile freight markets',
      'Ensuring compliance with financial regulations',
      'Optimizing working capital tied up in transportation',
      'Managing currency fluctuations in global operations',
      'Ensuring accurate financial reporting and controls',
      'Managing relationships with financial stakeholders',
      'Balancing cost control with operational requirements',
      'Ensuring proper financial controls and audits',
      'Managing financial performance metrics and KPIs',
      'Ensuring compliance with accounting standards',
      'Managing financial risk and exposure',
      'Ensuring proper financial planning and forecasting',
      'Managing financial relationships with carriers',
      'Ensuring proper financial controls and processes',
      'Managing financial performance and reporting',
      'Ensuring compliance with financial regulations',
      'Managing financial risk and exposure',
      'Ensuring proper financial planning and forecasting',
      'Managing financial relationships with stakeholders',
      'Ensuring proper financial controls and audits'
    ],
    toneProfile: 'Executive financial language emphasizing ROI, financial performance, and strategic financial planning. Use terms like "financial performance," "ROI," "strategic planning," "financial controls," and "stakeholder value." Focus on high-level financial outcomes.',
    keywords: ['financial', 'roi', 'performance', 'strategic', 'planning', 'controls', 'stakeholder', 'value']
  },
  {
    id: 'finance_upper_management',
    label: 'Upper Management - Finance',
    department: 'Finance',
    seniority: 'Upper Management',
    painPoints: [
      'Strategic & Financial Pressure: balancing short-term cost-cutting with long-term investment and growth strategies',
      'Strategic & Financial Pressure: increasing pressure from boards and investors for predictable financial performance',
      'Strategic & Financial Pressure: difficulty in forecasting accurately amid economic volatility, currency fluctuations, and market uncertainty',
      'Strategic & Financial Pressure: pressure to provide actionable insights beyond reporting (acting as a strategic partner vs. back-office)',
      'Operational Inefficiencies: reliance on outdated ERP/financial systems that require manual data reconciliation',
      'Operational Inefficiencies: complex, time-consuming month-end and quarter-end close processes',
      'Operational Inefficiencies: inconsistent processes across regions/business units, slowing down consolidation',
      'Data & Reporting Challenges: lack of real-time visibility into company supply chain health across operations',
      'Data & Reporting Challenges: struggles with data quality, accuracy, and consistency when pulling from multiple systems',
      'Data & Reporting Challenges: limited automation in reporting, leading to heavy reliance on spreadsheets',
      'Data & Reporting Challenges: difficulty delivering timely insights to executives due to manual reporting cycles',
      'Data & Reporting Challenges: regulatory reporting requirements that demand higher precision and audit-ability',
      'Technology Limitations: difficulty justifying ROI on finance digital transformation projects',
      'Technology Limitations: limited integration between ERP, BI, and planning systems',
      'Technology Limitations: struggles with implementing advanced analytics, AI, or automation due to data silos',
      'Talent & Organizational Issues: gaps in advanced analytics, automation, and digital finance capabilities among staff',
      'Talent & Organizational Issues: misalignment between finance priorities and operational/business unit leaders'
    ],
    toneProfile: 'Management financial language emphasizing departmental financial performance, team management, and financial controls. Use terms like "financial management," "departmental performance," "financial controls," and "team leadership." Focus on financial management and team leadership.',
    keywords: ['financial', 'management', 'departmental', 'controls', 'team', 'leadership', 'performance', 'planning']
  },
  {
    id: 'finance_middle_management',
    label: 'Middle Management - Finance',
    department: 'Finance',
    seniority: 'Middle Management',
    painPoints: [
      'Cost Control & Budget Management: freight spend is highly variable and difficult to forecast due to rate volatility',
      'Cost Control & Budget Management: hidden surcharges (fuel, accessorials, detention, demurrage) make budgeting unpredictable',
      'Cost Control & Budget Management: inability to accurately allocate transportation costs to specific products, regions, or business units',
      'Cost Control & Budget Management: difficulty validating that negotiated carrier rates are actually being applied in invoices',
      'Cost Control & Budget Management: pressure to reduce logistics costs while balancing service-level requirements',
      'Freight Audit & Payment Challenges: manual invoice reconciliation leading to errors and delays',
      'Freight Audit & Payment Challenges: high volume of freight invoices creates administrative burden',
      'Freight Audit & Payment Challenges: difficulty matching invoices to contracts, shipments, and POs',
      'Freight Audit & Payment Challenges: carrier overbilling or duplicate charges slipping through without proper audit controls',
      'Data & Reporting Limitations: limited visibility into total landed cost and how freight affects product margins',
      'Data & Reporting Limitations: inconsistent data across procurement, logistics, and finance systems',
      'Data & Reporting Limitations: difficulty producing accurate financial reports for leadership or regulators',
      'Data & Reporting Limitations: lack of standardized KPIs to measure cost efficiency of procurement decisions',
      'Data & Reporting Limitations: struggles to provide real-time reporting to support operational decision-making',
      'Risk & Compliance: exposure to financial risks from fuel price spikes, capacity shortages, or tariff changes',
      'Cross-Department Coordination: misalignment between finance, procurement, and operations on cost-saving initiatives',
      'Cross-Department Coordination: difficulty validating savings claimed by procurement against actual financial outcomes',
      'Cross-Department Coordination: pressure from CFO/board to demonstrate ROI of procurement projects',
      'Cross-Department Coordination: tension between finance\'s need for strict controls and operations\' need for agility',
      'Cross-Department Coordination: lack of clear accountability for freight cost overruns between departments',
      'Technology & Systems Gaps: reliance on outdated freight payment systems or spreadsheets',
      'Technology & Systems Gaps: poor integration between TMS, ERP, and financial systems',
      'Technology & Systems Gaps: difficulty adopting modern spend analytics tools without disrupting existing processes',
      'Technology & Systems Gaps: high IT/security hurdles to integrate external freight platforms with finance systems',
      'Strategic Pressures: increasing demand to make freight spend more predictable for earnings guidance',
      'Strategic Pressures: difficulty balancing short-term cost savings with long-term supply chain resilience',
      'Strategic Pressures: pressure to identify cost-saving opportunities in freight without undermining service quality',
      'Strategic Pressures: challenges in quantifying the financial impact of disruptions (e.g., port congestion, strikes)'
    ],
    toneProfile: 'Practical financial language emphasizing execution, financial analysis, and team coordination. Use terms like "financial analysis," "practical solutions," "team coordination," and "financial execution." Focus on practical financial management.',
    keywords: ['financial', 'analysis', 'practical', 'execution', 'team', 'coordination', 'management', 'solutions']
  },
  {
    id: 'finance_entry_level',
    label: 'Entry Level - Finance',
    department: 'Finance',
    seniority: 'Entry Level',
    painPoints: [
      'Operational & Process-Related Pain Points: heavy reliance on manual processes (Excel spreadsheets, email approvals, manual reconciliations)',
      'Operational & Process-Related Pain Points: time-consuming month-end and quarter-end closing cycles',
      'Operational & Process-Related Pain Points: difficulty consolidating financial data across multiple systems (ERP, procurement, logistics platforms)',
      'Operational & Process-Related Pain Points: lack of standardization in processes across business units or regions',
      'Operational & Process-Related Pain Points: high volume of repetitive tasks (invoice matching, expense tracking, reporting)',
      'Cost & Budget Management: limited visibility into actual vs. forecasted freight and procurement spend',
      'Cost & Budget Management: difficulty controlling costs when unexpected surcharges, detention, or demurrage occur',
      'Cost & Budget Management: budget overruns due to poor communication between operations and finance teams',
      'Cost & Budget Management: lack of granular cost allocation by lane, product, or business unit',
      'Cost & Budget Management: difficulty ensuring cost savings initiatives in procurement are actually realized and measurable',
      'Data & Reporting Challenges: fragmented systems leading to inconsistent data quality',
      'Data & Reporting Challenges: inability to generate real-time insights or dashboards for stakeholders',
      'Data & Reporting Challenges: long lead times to produce accurate reports for management',
      'Data & Reporting Challenges: difficulty tracking KPIs that connect financial metrics with supply chain performance',
      'Data & Reporting Challenges: struggles to translate complex financial data into actionable business insights for non-finance teams',
      'Compliance & Risk: difficulty auditing freight invoices and spotting discrepancies',
      'Compliance & Risk: risk exposure due to lack of oversight on vendor payments and contracts',
      'Technology Limitations: ERP systems that are outdated or poorly integrated with procurement/logistics platforms',
      'Technology Limitations: lack of automation for accounts payable and receivable processes',
      'Technology Limitations: difficulty implementing new finance tools due to steep learning curves or IT dependency',
      'Technology Limitations: limited ability to leverage predictive analytics for cost forecasting and scenario planning',
      'Collaboration & Communication: misalignment between finance, procurement, and operations on budgeting and cost drivers',
      'Collaboration & Communication: friction with non-financial stakeholders who may not understand finance constraints',
      'Collaboration & Communication: difficulty communicating the financial impact of supply chain disruptions to leadership',
      'Collaboration & Communication: slow approval cycles due to lack of clarity in financial authority levels',
      'Career & Role-Specific Pain Points: entry-level analysts bogged down with repetitive transactional work and limited exposure to strategic tasks',
      'Career & Role-Specific Pain Points: senior specialists/individual contributors struggling with balancing tactical reporting and higher-level analysis',
      'Career & Role-Specific Pain Points: lack of career progression or development opportunities in finance compared to other functions',
      'Career & Role-Specific Pain Points: feeling like "gatekeepers" rather than strategic partners, reducing job satisfaction',
      'Career & Role-Specific Pain Points: stress from constant deadlines and last-minute requests for data from leadership'
    ],
    toneProfile: 'Supportive financial language emphasizing learning, skill development, and professional growth. Use terms like "financial learning," "skill development," "professional growth," and "financial education." Focus on learning and development.',
    keywords: ['financial', 'learning', 'development', 'growth', 'education', 'skills', 'professional', 'support']
  },
  {
    id: 'finance_intern',
    label: 'Intern - Finance',
    department: 'Finance',
    seniority: 'Intern',
    painPoints: [
      'Understanding basic financial concepts',
      'Learning company financial processes',
      'Managing financial data entry and reporting',
      'Understanding financial regulations and compliance',
      'Learning to use financial systems and tools',
      'Understanding financial performance metrics',
      'Learning to analyze basic financial data',
      'Understanding financial risk management',
      'Managing financial documentation and records',
      'Learning to work with financial stakeholders',
      'Understanding financial planning and forecasting',
      'Learning to identify financial opportunities',
      'Understanding financial controls and processes',
      'Learning to manage financial projects',
      'Understanding financial reporting requirements',
      'Learning to work with different departments',
      'Understanding financial technology and tools',
      'Learning to manage financial deadlines',
      'Understanding financial compliance requirements',
      'Learning to adapt to changing financial requirements'
    ],
    toneProfile: 'Encouraging financial language emphasizing learning, exploration, and professional development. Use terms like "financial learning," "exploration," "discovery," and "professional development." Focus on learning and exploration.',
    keywords: ['financial', 'learning', 'exploration', 'discovery', 'development', 'professional', 'growth', 'opportunity']
  }
]

// Helper function to get persona by ID
export function getPersonaById(id: string): PersonaDefinition | undefined {
  return PERSONA_DEFINITIONS.find(persona => persona.id === id)
}

// Helper function to get personas by department
export function getPersonasByDepartment(department: 'Operations' | 'Finance'): PersonaDefinition[] {
  return PERSONA_DEFINITIONS.filter(persona => persona.department === department)
}

// Helper function to get personas by seniority
export function getPersonasBySeniority(seniority: 'C-Suite' | 'Upper Management' | 'Middle Management' | 'Entry Level' | 'Intern'): PersonaDefinition[] {
  return PERSONA_DEFINITIONS.filter(persona => persona.seniority === seniority)
}
